const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright'),assert=require('assert/strict'),fs=require('fs'),path=require('path');
let tests=[];function check(label,value){assert(value,label);tests.push(label)}
(async()=>{
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());const base=process.argv[2]||'http://localhost:4173/';await page.goto(base);await page.waitForFunction(()=>!!window.JCHStudio);
await page.locator('#loadProposal').click();await page.waitForFunction(()=>encanto.state.tables.length===23);check('Recupera la propuesta original con 23 mesas y 226 sillas',await page.evaluate(()=>encanto.state.tables.reduce((a,t)=>a+t.seats,0)===226&&encanto.state.floorAngle===90));
await page.waitForTimeout(150);await page.evaluate(()=>{window.testEditorRenders=0;window.testEditorRender=encanto.renderer.render;encanto.renderer.render=function(...args){window.testEditorRenders++;return window.testEditorRender.apply(this,args)}});await page.waitForTimeout(300);check('Editor en reposo libera el render para otras pestañas',await page.evaluate(()=>window.testEditorRenders===0));await page.locator('#roofcheck').check();await page.waitForFunction(()=>window.testEditorRenders>0);check('Cambiar la cubierta vuelve a dibujar el editor',await page.evaluate(()=>window.testEditorRenders>0));await page.locator('#roofcheck').uncheck();await page.evaluate(()=>{encanto.renderer.render=window.testEditorRender;delete window.testEditorRender;delete window.testEditorRenders});
await page.locator('#eventEdit').click();await page.locator('#eventNameInput').fill('Evento <script> y familia');await page.locator('#eventDateInput').fill('2026-11-15');await page.locator('#eventForm button[type=submit]').click();check('Nombre y fecha del evento se editan sin interpretar HTML',await page.locator('#eventTitle').innerText()==='Evento <script> y familia'&&await page.locator('#eventSubtitle').innerText()==='2026-11-15 · Salón Encanto');
await page.locator('#eventSave').click();await page.locator('#newEvent').click();check('Nueva distribución limpia sin perder el evento guardado',await page.evaluate(()=>encanto.state.tables.length===0));await page.locator('#eventsOpen').click();await page.locator('#eventsList button').filter({hasText:'Abrir'}).click();check('Mis eventos restaura distribución, título y fecha',await page.evaluate(()=>encanto.state.tables.length===23&&JCHStudio.meta().date==='2026-11-15'));
await page.locator('#tableSelect').selectOption('31');const before=await page.evaluate(()=>encanto.state.tables[0].angle);await page.locator('#table90').click();await page.waitForTimeout(100);await page.locator('#undo').click();check('Deshacer restaura la orientación anterior',await page.evaluate(before=>encanto.state.tables[0].angle===before,before));await page.locator('#redo').click();check('Rehacer recupera el cambio',await page.evaluate(before=>encanto.state.tables[0].angle===(before+90)%360,before));
await page.locator('#shareOpen').click();await page.waitForFunction(()=>document.getElementById('shareURL').value.includes('#jch='));const first=await page.locator('#shareURL').inputValue();const decoded=await page.evaluate(async url=>JCHShare.decode(url.split('#jch=')[1]),first);check('Enlace almacena la distribución completa y los datos del evento',decoded.layout.tables.length===23&&decoded.title==='Evento <script> y familia'&&decoded.date==='2026-11-15');
await page.locator('.share-settings summary').click();await page.locator('#share-light').selectOption('warm');await page.locator('#share-exposure').evaluate(e=>{e.value='125';e.dispatchEvent(new Event('change',{bubbles:true}))});await page.waitForTimeout(200);const sharedURL=await page.locator('#shareURL').inputValue(),frozen=await page.evaluate(async url=>JCHShare.decode(url.split('#jch=')[1]),sharedURL);check('La apariencia inicial se conserva en el enlace',frozen.settings.light==='warm'&&frozen.settings.exposure===125);
const client=await context.newPage();client.on('pageerror',e=>errors.push(e.message));await client.goto(sharedURL);await client.bringToFront();try{await client.waitForFunction(()=>window.__viewerReady||window.__viewerError,null,{timeout:60000,polling:100})}catch(e){console.log('VISOR DEBUG',errors,await client.locator('#loadLabel').innerText(),await client.locator('#progress').getAttribute('style'));await client.screenshot({path:'artifacts/visor-fallo.png'});throw e}check('Enlace abre el visor completo con WebGL y texturas',await client.evaluate(()=>__viewerReady&&__viewerStats.textureCount>=3&&__viewerStats.exposure===1.25&&__viewerStats.light==='warm'));check('Vista cliente presenta el nombre sin controles de edición',await client.locator('.brand strong').innerText()==='Evento <script> y familia'&&await client.locator('#tableW').count()===0);
await page.locator('[data-close=shareDialog]').click();await page.locator('#tableSelect').selectOption('31');await page.locator('#tableW').fill('1.7');await page.locator('#tableW').press('Tab');check('Editar el evento no altera el enlace ya generado',await page.evaluate(async url=>{const p=await JCHShare.decode(url.split('#jch=')[1]);return p.layout.tables[0].w===1.2&&encanto.state.tables[0].w===1.7},sharedURL));
await client.bringToFront();await client.locator('[data-view=top]').click();await client.waitForFunction(()=>__viewerStats.view==='top'&&!__viewerStats.animating);check('Planta funciona en la presentación',await client.evaluate(()=>__viewerStats.view==='top'));await client.locator('[data-view=front]').click();await client.waitForFunction(()=>__viewerStats.view==='front'&&!__viewerStats.animating);check('Vista de frente funciona',await client.evaluate(()=>__viewerStats.view==='front'));await client.locator('[data-view=side]').click();await client.waitForFunction(()=>__viewerStats.view==='side'&&!__viewerStats.animating);check('Vista lateral funciona',await client.evaluate(()=>__viewerStats.view==='side'));
await client.locator('[data-view=general]').click();await client.waitForFunction(()=>__viewerStats.view==='general'&&!__viewerStats.animating);const radius=await client.evaluate(()=>__viewerStats.radius);await client.locator('#zoomIn').click();await client.waitForFunction(r=>__viewerStats.radius<r,radius);check('Acercar reduce la distancia de la cámara',await client.evaluate(r=>__viewerStats.radius<r,radius));await client.locator('#zoomOut').click();
await client.locator('#roofQuick').click();check('Cubierta se muestra y actualiza su botón',await client.locator('#roofQuick').getAttribute('aria-pressed')==='true');await client.locator('#settings').click();await client.locator('#wall').uncheck();await client.waitForFunction(()=>__viewerStats.wall===false);check('Ocultar muro actualiza la escena',await client.evaluate(()=>!__viewerStats.wall));await client.locator('#wall').check();await client.locator('#cut').check();await client.locator('#cutHeight').evaluate(e=>{e.value='1.8';e.dispatchEvent(new Event('input',{bubbles:true}))});await client.waitForFunction(()=>__viewerStats.clipped&&Math.abs(__viewerStats.cutHeight-1.8)<.01);check('Corte horizontal usa la altura indicada',await client.evaluate(()=>__viewerStats.clipped&&Math.abs(__viewerStats.cutHeight-1.8)<.01));await client.locator('#cut').uncheck();
await client.locator('#quality').selectOption('low');await client.locator('#background').selectOption('dark');await client.locator('#grid').check();await client.locator('#shadows').uncheck();await client.locator('#shadows').check();await client.locator('[data-light=day]').click();await client.waitForFunction(()=>__viewerStats.light==='day');check('Calidad, fondo, rejilla, sombras e iluminación se pueden cambiar',await client.evaluate(()=>__viewerStats.light==='day'&&document.getElementById('quality').value==='low'&&document.getElementById('grid').checked));
await client.locator('#reset').click();await client.locator('#closePanel').click();await client.locator('[data-view=interior]').click();await client.waitForFunction(()=>__viewerStats.walk);const eye=await client.evaluate(()=>__viewerStats.camera);const forward=await client.locator('[data-move=forward]').boundingBox();await client.mouse.move(forward.x+forward.width/2,forward.y+forward.height/2);await client.mouse.down();await client.waitForTimeout(300);await client.mouse.up();await client.waitForFunction(eye=>JSON.stringify(__viewerStats.camera)!==JSON.stringify(eye),eye);check('Modo interior recorre el salón',await client.evaluate(eye=>__viewerStats.walk&&JSON.stringify(__viewerStats.camera)!==JSON.stringify(eye),eye));
await client.locator('[data-view=general]').click();await client.waitForFunction(()=>__viewerStats.view==='general'&&!__viewerStats.animating);await client.locator('#clean').click();check('Vista limpia oculta la interfaz',await client.locator('body').getAttribute('class').then(c=>c.includes('clean')));await client.locator('#restoreUI').click();check('Los controles se pueden recuperar',await client.locator('#settings').isVisible());
await client.locator('#settings').click();const pngWait=client.waitForEvent('download');await client.locator('#capture').click();const png=await pngWait;await png.saveAs('artifacts/presentation.png');check('Guardar imagen produce un PNG válido',fs.readFileSync('artifacts/presentation.png').subarray(1,4).toString()==='PNG');
await page.locator('#shareOpen').click();await page.waitForFunction(()=>document.getElementById('shareURL').value.includes('#jch='));const dl=page.waitForEvent('download');await page.locator('#shareHTML').click();const htmlDownload=await dl;await htmlDownload.saveAs('artifacts/presentation-offline.html');const offlineText=fs.readFileSync('artifacts/presentation-offline.html','utf8');check('HTML descargado contiene modelo y no depende de recursos externos',offlineText.includes('id="modelData"')&&!/<script[^>]+src=|<link[^>]+href=/.test(offlineText));
const offlineContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,offline:true}),offline=await offlineContext.newPage(),requests=[];offline.on('pageerror',e=>errors.push(e.message));offline.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});await offline.goto('file://'+path.resolve('artifacts/presentation-offline.html'));await offline.bringToFront();await offline.waitForFunction(()=>window.__viewerReady||window.__viewerError,null,{timeout:60000,polling:100});check('HTML funciona sin red en un contexto móvil independiente',await offline.evaluate(()=>__viewerReady&&__viewerStats.textureCount>=3)&&requests.length===0);check('Visor móvil cabe en pantalla sin desplazamiento horizontal',await offline.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await offline.locator('#settings').tap();await offline.locator('#background').selectOption('white');await offline.locator('#closePanel').tap();await offline.locator('[data-view=top]').tap();await offline.waitForTimeout(650);check('Controles táctiles funcionan en el visor offline',await offline.evaluate(()=>__viewerStats.view==='top'));await offline.locator('[data-view=general]').tap();await offline.waitForTimeout(650);await offline.screenshot({path:'artifacts/jch3d_visor_mobile.png'});
// Hostile and truncated links fail with readable messages, not an empty scene.
const bad=await context.newPage();await bad.goto(new URL('/presentacion/',base).href+'#jch=d.bad_token');await bad.waitForFunction(()=>!!window.__viewerError);check('Enlace inválido muestra un error y permite reintentar',await bad.locator('#retry').isVisible()&&await bad.evaluate(()=>!__viewerReady));await bad.close();
check('Codec sin compresión conserva una distribución pequeña',await page.evaluate(async()=>{const p=JCHStudio.presentation();p.layout.tables=p.layout.tables.slice(0,2);const compress=window.CompressionStream;window.CompressionStream=undefined;try{const token=await JCHShare.encode(p),q=await JCHShare.decode(token);return token.startsWith('u.')&&q.layout.tables.length===2}finally{window.CompressionStream=compress}}));
check('Codec comprimido conserva 100 mesas',await page.evaluate(async()=>{const p=JCHStudio.presentation(),t=p.layout.tables[0];p.layout.tables=Array.from({length:100},(_,i)=>({...t,id:i+1,label:'Invitados '+i}));const token=await JCHShare.encode(p),q=await JCHShare.decode(token);return q.layout.tables.length===100}));
await client.bringToFront();await client.locator('#tour').click();await client.waitForFunction(()=>__viewerStats.tour);check('Recorrido automático inicia',await client.evaluate(()=>__viewerStats.tour));await client.locator('#tour').click();await client.waitForFunction(()=>!__viewerStats.tour);check('Recorrido automático puede detenerse',await client.evaluate(()=>!__viewerStats.tour));
if(await client.locator('#closePanel').isVisible())await client.locator('#closePanel').click();await client.setViewportSize({width:1440,height:1000});await client.locator('[data-view=general]').click();await client.waitForFunction(()=>__viewerStats.view==='general'&&!__viewerStats.animating);await client.screenshot({path:'artifacts/jch3d_visor_compartido.png'});
check('Sin excepciones JavaScript en los flujos válidos',errors.length===0);fs.writeFileSync('artifacts/presentation-tests.json',JSON.stringify({passed:tests.length,tests,errors,date:new Date().toISOString()},null,2));console.log(JSON.stringify({passed:tests.length,tests,errors},null,2));await browser.close();
})().catch(e=>{console.error(e);console.log('Pruebas antes del fallo',tests);process.exit(1)});
