
(()=>{'use strict';
const $=id=>document.getElementById(id),vp=$('viewport');
const state={version:1,extent:'inside',stageH:.65,rampL:4.5,floorX:11.5,floorZ:10,floorAngle:0,tables:[]};
let scene,camera,renderer,model,roofGroup,dimGroup,tableGroup,floorGroup,floorDims,floorSelection,selected=null,mode='iso',nextId=1;
const tableDefaults={shape:'round',w:1.8,d:1.8,seats:10,angle:0,chairGap:.08,chairWidth:.42,chairDepth:.42,tableHeight:.77,tableColor:'#f4eee1',chairColor:'#eee9dc',cushionColor:'#fffdf4',label:''};
let tableMode='new',newTableDraft={...tableDefaults},editorSyncing=false,pendingTables=new Set(),tableFrame=0;
// The editor is a static scene. Render only after a visual change so a second
// presentation tab can use the GPU, and idle editors do not drain phone batteries.
let renderFrame=0;
function requestEditorRender(){if(!renderFrame&&renderer&&!document.hidden)renderFrame=requestAnimationFrame(()=>{renderFrame=0;if(!document.hidden)renderer.render(scene,camera)})}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)requestEditorRender()});
JCHModel.assetsReady.then(requestEditorRender).catch(()=>{});
const sharedBox=new THREE.BoxGeometry(1,1,1),sharedRound=new THREE.CylinderGeometry(.5,.5,.07,48),chairGeometry=createTiffanyGeometry(),footprintCache=new WeakMap();
const sharedGeometry=new Set([sharedBox,sharedRound,chairGeometry]);
const tableFields={w:['tableW','tableWRange'],d:['tableD','tableDRange'],seats:['seats','seatsRange'],chairGap:['chairGap','chairGapRange'],angle:['tableAngle','tableAngleRange'],chairWidth:['chairWidth','chairWidthRange'],chairDepth:['chairDepth','chairDepthRange'],tableHeight:['tableHeight','tableHeightRange']};
function createTiffanyGeometry(){
 const pieces=[];
 function rod(a,b,r=.014){a=new THREE.Vector3(...a);b=new THREE.Vector3(...b);const g=new THREE.CylinderGeometry(r,r,a.distanceTo(b),6);const m=new THREE.Matrix4().compose(a.clone().add(b).multiplyScalar(.5),new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize()),new THREE.Vector3(1,1,1));pieces.push(g.toNonIndexed().applyMatrix4(m));g.dispose()}
 for(const x of [-.19,.19]){rod([x,0,-.19],[x,.45,-.19],.017);rod([x,0,.19],[x,.99,.19],.017);rod([x,.2,-.19],[x,.2,.19]);}
 for(const z of [-.19,.19])rod([-.19,.2,z],[.19,.2,z]);
 for(const y of [.48,.68,.82,.96])rod([-.19,y,.19],[.19,y,.19],y===.96?.02:.014);
 for(const x of [-.095,0,.095])rod([x,.48,.19],[x,.96,.19],.01);
 for(const x of [-.19,.19])for(const y of [.57,.75,.91]){const g=new THREE.SphereGeometry(.023,6,4).toNonIndexed();g.translate(x,y,.19);pieces.push(g)}
 const g=new THREE.BufferGeometry();for(const key of ['position','normal','uv']){const length=pieces.reduce((n,p)=>n+p.attributes[key].array.length,0),a=new Float32Array(length);let offset=0;for(const p of pieces){a.set(p.attributes[key].array,offset);offset+=p.attributes[key].array.length}g.setAttribute(key,new THREE.BufferAttribute(a,key==='uv'?2:3))}pieces.forEach(p=>p.dispose());return g;
}
const normalizeTable=JCHModel.normalizeTable,chairLayout=JCHModel.chairLayout;
const tableNumber=t=>JCHModel.tableNumber(state,t);
function makeTable(t){
 const group=new THREE.Group();group.position.set(t.x,0,t.z);group.rotation.y=THREE.MathUtils.degToRad(t.angle);group.userData.tableId=t.id;group.name='Mesa '+tableNumber(t);
 const topMat=mat(selected===t.id?0xd5b85c:t.tableColor),chairMat=mat(t.chairColor,{roughness:.45}),cushionMat=mat(t.cushionColor);group.userData.topMaterial=topMat;group.userData.materials=[topMat,chairMat,cushionMat];
 if(t.shape==='round'){const top=new THREE.Mesh(sharedRound,topMat);top.position.y=t.tableHeight;top.scale.set(t.w,1,t.w);top.name='Mesa redonda';top.castShadow=true;top.receiveShadow=true;group.add(top);box(.12,t.tableHeight-.035,.12,0,(t.tableHeight-.035)/2,0,materials.steel,group)}else{box(t.w,.07,t.d,0,t.tableHeight,0,topMat,group,'Mesa '+t.shape);for(const x of [-t.w*.4,t.w*.4])for(const z of [-t.d*.36,t.d*.36])box(.07,t.tableHeight-.035,.07,x,(t.tableHeight-.035)/2,z,materials.steel,group)}
 chairLayout(t).forEach((p,i)=>{const chair=new THREE.Group();chair.name='Silla Tiffany '+(i+1);chair.userData.chairIndex=i;chair.position.set(p.x,0,p.z);chair.rotation.y=p.angle;chair.scale.set(t.chairWidth/.42,1,t.chairDepth/.42);const frame=new THREE.Mesh(chairGeometry,chairMat);frame.name='Estructura Tiffany';frame.castShadow=true;chair.add(frame);box(.4,.06,.4,0,.45,0,cushionMat,chair,'Cojín Tiffany');group.add(chair)});
 JCHModel.addTableBadge(group,t,tableNumber(t));label('M'+tableNumber(t)+(t.label?' · '+t.label:''),0,Math.max(1.23,t.tableHeight+.4),0,.3,'#304b37',group);tableGroup.add(group);return group;
}
function disposeTable(group){group.traverse(o=>{if(o.geometry&&!o.isSprite&&!sharedGeometry.has(o.geometry))o.geometry.dispose();if(o.isSprite){o.material.map.dispose();o.material.dispose()}});group.userData.materials.forEach(m=>{m.map?.dispose();m.dispose()})}
function updateTables(ids){const wanted=ids?new Set(ids):null;for(const g of [...tableGroup.children])if(!wanted||wanted.has(g.userData.tableId)){disposeTable(g);tableGroup.remove(g)}for(const t of state.tables)if(!wanted||wanted.has(t.id))makeTable(t);tableGroup.updateMatrixWorld(true);updateStatus();persist()}
function queueTables(ids){ids.forEach(id=>pendingTables.add(id));if(!tableFrame)tableFrame=requestAnimationFrame(()=>{tableFrame=0;const ids=[...pendingTables];pendingTables.clear();updateTables(ids)})}
function flushTables(){if(tableFrame){cancelAnimationFrame(tableFrame);tableFrame=0;const ids=[...pendingTables];pendingTables.clear();updateTables(ids)}}
function convexHull(points){const sorted=points.slice().sort((a,b)=>a.x-b.x||a.z-b.z),cross=(a,b,c)=>(b.x-a.x)*(c.z-a.z)-(b.z-a.z)*(c.x-a.x);let lo=[],hi=[];for(const p of sorted){while(lo.length>=2&&cross(lo.at(-2),lo.at(-1),p)<=0)lo.pop();lo.push(p)}for(const p of sorted.slice().reverse()){while(hi.length>=2&&cross(hi.at(-2),hi.at(-1),p)<=0)hi.pop();hi.push(p)}return lo.slice(0,-1).concat(hi.slice(0,-1))}
function tableFootprint(t){const key=[t.x,t.z,t.w,t.d,t.shape,t.seats,t.angle,t.chairGap,t.chairWidth,t.chairDepth,t.chairMode,t.chairArcStart,t.chairArcSpan,JSON.stringify(t.chairSides),JSON.stringify(t.customChairs)].join('|'),cached=footprintCache.get(t);if(cached?.key===key)return cached.points;const points=[];if(t.shape==='round'){for(let i=0;i<32;i++){const a=i/32*Math.PI*2;points.push({x:Math.cos(a)*(t.w/2+.02),z:Math.sin(a)*(t.w/2+.02)})}}else for(const x of [-t.w/2,t.w/2])for(const z of [-t.d/2,t.d/2])points.push({x,z});for(const p of chairLayout(t))for(const x of [-t.chairWidth/2,t.chairWidth/2])for(const z of [-t.chairDepth/2,t.chairDepth/2+.025])points.push({x:p.x+Math.cos(p.angle)*x+Math.sin(p.angle)*z,z:p.z-Math.sin(p.angle)*x+Math.cos(p.angle)*z});const a=THREE.MathUtils.degToRad(t.angle),out=convexHull(points).map(p=>({x:t.x+Math.cos(a)*p.x+Math.sin(a)*p.z,z:t.z-Math.sin(a)*p.x+Math.cos(a)*p.z}));footprintCache.set(t,{key,points:out});return out}
function rectangleFootprint(xa,za,xb,zb,angle=0,cx=0,cz=0){const a=THREE.MathUtils.degToRad(angle);return [[xa,za],[xb,za],[xb,zb],[xa,zb]].map(([x,z])=>({x:cx+Math.cos(a)*x+Math.sin(a)*z,z:cz-Math.sin(a)*x+Math.cos(a)*z}))}
function polygonsOverlap(a,b){const ax=a.map(v=>v.x),az=a.map(v=>v.z),bx=b.map(v=>v.x),bz=b.map(v=>v.z);if(Math.max(...ax)<=Math.min(...bx)||Math.max(...bx)<=Math.min(...ax)||Math.max(...az)<=Math.min(...bz)||Math.max(...bz)<=Math.min(...az))return false;for(const poly of [a,b])for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length],ax=-(q.z-p.z),az=q.x-p.x;if(Math.abs(ax)+Math.abs(az)<1e-9)continue;const aa=a.map(v=>v.x*ax+v.z*az),bb=b.map(v=>v.x*ax+v.z*az);if(Math.max(...aa)<=Math.min(...bb)+1e-8||Math.max(...bb)<=Math.min(...aa)+1e-8)return false}return true}
function collision(t,ignoreSelf=true){const W=state.extent==='inside'?20:23,p=tableFootprint(t),cx=(W+3)/2;if(p.some(v=>v.x<3.15||v.x>W-.25||v.z<.2||v.z>19.4))return 'fuera del área libre';if(polygonsOverlap(p,rectangleFootprint(-3.65,-2.5,3.65,2.5,state.floorAngle,state.floorX,state.floorZ)))return 'cruce con la pista';if(polygonsOverlap(p,rectangleFootprint(3,18-state.rampL,4.6,19.25)))return 'cruce con la rampa';const accessEnd=Math.max(0,state.floorZ-floorBounds(state.floorAngle).z);if(accessEnd>0&&polygonsOverlap(p,rectangleFootprint(cx-1.25,0,cx+1.25,accessEnd)))return 'cruce con el acceso central';for(const other of state.tables){if(ignoreSelf&&other.id===t.id)continue;if(polygonsOverlap(p,tableFootprint(other)))return 'cruce entre mesas o sillas'}return ''}
function editorTargets(){return tableMode==='all'?state.tables:tableMode==='single'?state.tables.filter(t=>t.id===selected):[]}
function setTableMode(value){flushTables();if(value==='single'&&!state.tables.some(t=>t.id===selected))return;tableMode=value;if(value!=='single'){selected=null;highlightTables()}updateStatus();syncTableEditor()}
function highlightTables(){requestEditorRender();for(const g of tableGroup.children){const t=state.tables.find(t=>t.id===g.userData.tableId);g.userData.topMaterial.color.set(g.userData.tableId===selected?0xd5b85c:t.tableColor)}}
function syncTableEditor(){editorSyncing=true;const targets=editorTargets(),first=tableMode==='new'?newTableDraft:targets[0],all=tableMode==='all';if(!first&&tableMode==='single'){tableMode='new';editorSyncing=false;return syncTableEditor()}for(const [id,value]of [['newTable','new'],['editOne','single'],['editAll','all']]){$(id).classList.toggle('active',tableMode===value);$(id).setAttribute('aria-pressed',String(tableMode===value))}$('editOne').disabled=!state.tables.some(t=>t.id===selected);$('editorTitle').textContent=tableMode==='new'?'Configurar una mesa nueva':all?'Editar todas las mesas ('+targets.length+')':'Editar mesa '+tableNumber(selected);$('editorNote').textContent=all?'Cada control cambia ese ajuste en todas las mesas. Sus posiciones se conservan. “Varios” indica valores diferentes.':tableMode==='new'?'Configura la mesa y sus sillas antes de agregarla.':'Los cambios se aplican al instante. Arrastra la mesa para moverla.';$('tableParameters').classList.toggle('hidden',!first);$('emptyEditor').classList.toggle('hidden',!!first);$('keepShape').hidden=!all;$('add').classList.toggle('hidden',tableMode!=='new');$('duplicate').classList.toggle('hidden',tableMode!=='single');$('labelField').classList.toggle('hidden',all);if(first){const mixedShape=all&&targets.some(t=>t.shape!==first.shape),shape=mixedShape?'keep':first.shape;$('shape').value=shape;$('widthLabel').textContent=shape==='round'?'Diámetro (m)':shape==='square'?'Lado (m)':shape==='keep'?'Diámetro / largo / lado (m)':'Largo (m)';$('depthField').classList.toggle('hidden',all?!targets.some(t=>t.shape==='rectangle'):shape!=='rectangle');for(const [key,ids]of Object.entries(tableFields)){const values=all&&key==='d'?targets.filter(t=>t.shape==='rectangle'):targets;const v=values[0]||first;for(const id of ids)if(document.activeElement!==$(id))$(id).value=v[key];$('mixed-'+key).classList.toggle('hidden',!all||!values.some(t=>t[key]!==v[key]))}for(const key of ['tableColor','chairColor','cushionColor','label'])if(document.activeElement!==$(key))$(key).value=first[key]}editorSyncing=false;document.dispatchEvent(new CustomEvent('jch:selection'))}
function tableError(message=''){$('editorError').textContent=message;$('editorError').classList.toggle('hidden',!message)}
function editTableField(key,value){if(editorSyncing)return;const targets=tableMode==='new'?[{...newTableDraft,id:1,x:6,z:3}]:editorTargets(),eligible=key==='d'?targets.filter(t=>t.shape==='rectangle'):targets;try{const proposed=eligible.map(t=>normalizeTable({...t,[key]:value}));if(tableMode==='new'){if(proposed[0])newTableDraft={...proposed[0]}}else{eligible.forEach((t,i)=>Object.assign(t,proposed[i]));queueTables(eligible.map(t=>t.id));persist()}tableError();syncTableEditor();updateStatus()}catch(e){tableError(e.message)}}
function editTableShape(shape){if(shape==='keep')return;const targets=tableMode==='new'?[{...newTableDraft,id:1,x:6,z:3}]:editorTargets();try{const proposed=targets.map(t=>normalizeTable({...t,shape,...(tableMode==='new'?{w:shape==='rectangle'?2.4:1.8,d:shape==='rectangle'?1.2:1.8,seats:shape==='round'?10:8}:{})}));if(tableMode==='new')newTableDraft={...proposed[0]};else{targets.forEach((t,i)=>Object.assign(t,proposed[i]));queueTables(targets.map(t=>t.id));persist()}tableError();syncTableEditor();updateStatus()}catch(e){tableError(e.message)}}
function turnTables(delta){if(tableMode==='new')return editTableField('angle',normalizeAngle(newTableDraft.angle+delta));const targets=editorTargets();targets.forEach(t=>t.angle=normalizeAngle(t.angle+delta));queueTables(targets.map(t=>t.id));persist();syncTableEditor();updateStatus()}
function addTable(prototype=newTableDraft){flushTables();if(state.tables.length>=100){tableError('El editor admite hasta 100 mesas');return}let t;try{t=normalizeTable({...prototype,id:nextId,x:6,z:3})}catch(e){tableError(e.message);return}let found=false,W=state.extent==='inside'?20:23;for(let z=.8;z<19&&!found;z+=.3)for(let x=3.6;x<W-.3;x+=.3){t.x=Math.round(x*10)/10;t.z=Math.round(z*10)/10;if(!collision(t,false)){found=true;break}}if(!found){tableError('No se encontró espacio libre. Reduce las dimensiones o reorganiza las mesas.');return}state.tables.push(t);nextId++;selected=t.id;tableMode='single';tableError();updateTables();setNavigation('rotate');updateHint()}
function bindTableEditor(){for(const [id,scope]of [['newTable','new'],['editOne','single'],['editAll','all']])$(id).onclick=()=>setTableMode(scope);$('shape').onchange=()=>editTableShape($('shape').value);for(const [key,ids]of Object.entries(tableFields))for(const id of ids){$(id).oninput=()=>editTableField(key,Number($(id).value));$(id).onchange=()=>editTableField(key,Number($(id).value));$(id).onblur=syncTableEditor}for(const key of ['tableColor','chairColor','cushionColor','label'])$(key).oninput=()=>editTableField(key,$(key).value);$('tableLeft').onclick=$('quickTableLeft').onclick=()=>turnTables(-15);$('tableRight').onclick=$('quickTableRight').onclick=()=>turnTables(15);$('table90').onclick=()=>turnTables(90);$('add').onclick=()=>addTable();$('duplicate').onclick=()=>{const t=state.tables.find(t=>t.id===selected);if(t)addTable({...t,label:t.label?t.label.slice(0,32)+' (copia)':''})};syncTableEditor()}

const materials={},target=new THREE.Vector3(10,0,-9),ray=new THREE.Raycaster(),mouse=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
let theta=-.72,phi=.95,radius=43,topDistance=52,entryYaw=0,entryPitch=-.041,navMode='rotate',down=null,tableDrag=null,touches=new Map(),pinch=null;const entryOffset=new THREE.Vector3();
function mat(color,other={}){return new THREE.MeshStandardMaterial({color,roughness:.85,...other})}
const C={grass:0x648044,stone:0xe5e3d7,stage:0xa87757,cream:0xf2f0e7,white:0xeceee7,red:0xb52b39,teal:0x1693a3,yellow:0xefd535,dark:0x252a2b,steel:0xe8e9df};
function texture(kind){const c=document.createElement('canvas');c.width=c.height=512;let g=c.getContext('2d');let seed=38;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647};if(kind==='grass'){g.fillStyle='#5b793f';g.fillRect(0,0,512,512);for(let i=0;i<26000;i++){let v=rand();g.strokeStyle=v>.5?'rgba(170,180,100,.2)':'rgba(36,57,27,.23)';g.beginPath();let x=rand()*512,y=rand()*512;g.moveTo(x,y);g.lineTo(x+rand()*3-1.5,y-2-rand()*5);g.stroke()}}else{g.fillStyle='#dddccf';g.fillRect(0,0,512,512);for(let row=0;row<9;row++){for(let col=-1;col<8;col++){let x=col*75+(row%2?30:0),y=row*60;g.fillStyle=['#484b46','#636760','#757871','#525751'][Math.floor(rand()*4)];g.beginPath();g.moveTo(x+5,y+5);g.lineTo(x+67,y+2+rand()*8);g.lineTo(x+72,y+47);g.lineTo(x+40,y+57);g.lineTo(x+3,y+49);g.closePath();g.fill()}}}let t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;t.repeat.set(kind==='grass'?8:7,kind==='grass'?8:2);return t}
function box(w,h,d,x,y,z,m,parent=model,name=''){let o=new THREE.Mesh(sharedBox,m);o.position.set(x,y,z);o.scale.set(w,h,d);o.castShadow=true;o.receiveShadow=true;o.name=name;parent.add(o);return o}
function beam(a,b,r,m,parent=model){a=new THREE.Vector3(...a);b=new THREE.Vector3(...b);let o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,a.distanceTo(b),8),m);o.position.copy(a).add(b).multiplyScalar(.5);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.sub(a).normalize());o.castShadow=true;parent.add(o);return o}
function label(text,x,y,z,size=1,color='#3b5041',parent=dimGroup){const c=document.createElement('canvas');c.width=1024;c.height=160;const g=c.getContext('2d');g.fillStyle='rgba(250,250,242,.94)';g.fillRect(0,0,1024,160);g.fillStyle=color;g.font='500 66px Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(text,512,84);let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const o=new THREE.Sprite(new THREE.SpriteMaterial({map:t,depthTest:false}));o.position.set(x,y,z);o.scale.set(size*5.4,size*.84,1);o.renderOrder=100;parent.add(o);return o}
function line(a,b,color=0x3d5140,parent=dimGroup){let g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...a),new THREE.Vector3(...b)]);parent.add(new THREE.Line(g,new THREE.LineBasicMaterial({color})))}
function dim(a,b,text,pos,parent=dimGroup){line(a,b,0x3d5140,parent);const along=new THREE.Vector3(...b).sub(new THREE.Vector3(...a)).normalize();let cross=new THREE.Vector3(-along.z,0,along.x).multiplyScalar(.17);for(const p of [a,b])line([p[0]+cross.x,p[1],p[2]+cross.z],[p[0]-cross.x,p[1],p[2]-cross.z],0x3d5140,parent);label(text,...pos,1,'#3b5041',parent)}
function archBoard(x,z){const sh=new THREE.Shape();sh.moveTo(-1.95,0);sh.lineTo(-1.95,3.8);sh.lineTo(1.95,3.8);sh.lineTo(1.95,0);sh.lineTo(1.35,0);sh.lineTo(1.35,1.0);sh.quadraticCurveTo(1.35,2.05,.55,2.05);sh.lineTo(-.55,2.05);sh.quadraticCurveTo(-1.35,2.05,-1.35,1);sh.lineTo(-1.35,0);sh.closePath();let o=new THREE.Mesh(new THREE.ExtrudeGeometry(sh,{depth:.12,bevelEnabled:false}),materials.teal);o.position.set(x,1.2,z);o.name='Arco decorativo de trajinera';model.add(o);beam([x-1.95,1.2,z-.02],[x-1.95,5,z-.02],.06,materials.yellow);beam([x+1.95,1.2,z-.02],[x+1.95,5,z-.02],.06,materials.yellow);beam([x-1.95,5,z-.02],[x+1.95,5,z-.02],.06,materials.yellow);
const c=document.createElement('canvas');c.width=1024;c.height=180;let ctx=c.getContext('2d');ctx.fillStyle='#166c80';ctx.fillRect(0,0,1024,180);ctx.strokeStyle='#e5c834';ctx.lineWidth=18;ctx.strokeRect(7,7,1010,166);ctx.fillStyle='#f6f0dd';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 69px Georgia';ctx.fillText('XOCHIMILCO MÁGICO',512,95);let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;let s=new THREE.Mesh(new THREE.PlaneGeometry(3.6,.65),new THREE.MeshStandardMaterial({map:t,side:THREE.DoubleSide}));s.position.set(x,4.62,z-.04);s.rotation.y=0;model.add(s);
const c2=document.createElement('canvas');c2.width=1024;c2.height=250;let q=c2.getContext('2d');q.fillStyle='#578258';q.fillRect(0,0,1024,250);q.fillStyle='#faf2d4';q.font='bold 160px Georgia';q.textAlign='center';q.textBaseline='middle';q.fillText('AMELIA',512,137);let t2=new THREE.CanvasTexture(c2);t2.colorSpace=THREE.SRGBColorSpace;s=new THREE.Mesh(new THREE.PlaneGeometry(2.65,.72),new THREE.MeshStandardMaterial({map:t2,side:THREE.DoubleSide}));s.position.set(x,3.75,z-.045);s.rotation.y=0;model.add(s);}
function foliage(x,z,h=2.2){let g=new THREE.Group();g.position.set(x,0,z);model.add(g);box(.25,h,.25,0,h/2,0,materials.wood,g);let o=new THREE.Mesh(new THREE.IcosahedronGeometry(.9,1),materials.leaf);o.scale.set(1,h*.58,1);o.position.y=h*.77;g.add(o)}
function ramp(){let z1=18-state.rampL,z2=18,x1=3,x2=4.4,h=state.stageH;let pts=[x1,0,z1,x2,0,z1,x1,h,z2,x2,h,z2,x1,0,z2,x2,0,z2];let ix=[0,2,1,1,2,3,0,4,2,1,3,5,2,4,3,3,4,5,0,1,4,1,5,4];let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));g.setIndex(ix);g.setAttribute('uv',new THREE.Float32BufferAttribute([0,0,1,0,0,1,1,1,0,1,1,1],2));g.computeVertexNormals();let o=new THREE.Mesh(g,materials.grass);o.castShadow=true;o.receiveShadow=true;o.name='Rampa lateral izquierda aproximada';model.add(o);box(1.4,h,1.2,3.7,h/2,18.6,materials.stage);for(const x of [3.05,4.35]){beam([x,.85,z1],[x,h+.85,z2],.035,materials.steel);for(let i=0;i<4;i++){let t=i/3,z=z1+(z2-z1)*t,base=h*t;beam([x,base,z],[x,base+.85,z],.025,materials.steel)}}}
let venue;
function build(){flushTables();if(venue)venue.dispose();else if(model)scene.remove(model);venue=JCHModel.createVenue(state,{scene,roof:$('roofcheck').checked,dimensions:$('dimcheck').checked});({model,roofGroup,dimGroup,tableGroup,floorGroup,floorDims,floorSelection}=venue);Object.assign(materials,venue.materials);$('totalbadge').textContent=(state.extent==='inside'?20:23)+' × 20 m';updateStatus();}
function updateStatus(){requestEditorRender();const bad=state.tables.filter(t=>collision(t)),seats=state.tables.reduce((n,t)=>n+t.seats,0);$('status').textContent='Mesas: '+state.tables.length+' · Sillas: '+seats+(bad.length?' · Revisar: '+bad.map(t=>'M'+tableNumber(t)+' ('+collision(t)+')').join(', '):' · Sin cruces de huellas detectados');$('status').classList.toggle('warning',bad.length>0);const t=state.tables.find(t=>t.id===selected),floor=selected==='floor';if(!t&&!floor)selected=null;const select=$('tableSelect'),signature=JSON.stringify(state.tables.map(t=>[t.id,t.label]));if(select.dataset.signature!==signature){select.replaceChildren(new Option('Ninguna',''),...state.tables.map(t=>new Option('M'+tableNumber(t)+(t.label?' · '+t.label:''),String(t.id))));select.dataset.signature=signature}select.value=t?String(selected):'';$('selected').classList.toggle('hidden',!t);$('tableActions').classList.toggle('hidden',!t&&!floor);$('quickDelete').classList.toggle('hidden',!t);$('quickFloor').classList.toggle('hidden',!floor);$('quickTable').classList.toggle('hidden',!t);$('selectFloor').classList.toggle('active',floor);if(floor)$('quicksel').textContent='Pista · '+state.floorAngle+'°';if(floorSelection)floorSelection.visible=floor;syncFloor();if(t){$('selname').textContent='Mesa '+tableNumber(t)+' · '+t.seats+' sillas';$('quicksel').textContent='Mesa '+tableNumber(t)+' · '+t.angle+'°';for(const [id,key]of [['tx','x'],['tz','z']])if(document.activeElement!==$(id))$(id).value=t[key].toFixed(2)}syncTableEditor()}
function cameraUpdate(){if(mode==='top'){camera.position.set(target.x,topDistance,target.z+.001);camera.up.set(0,0,-1);camera.lookAt(target)}else if(mode==='entry'){camera.up.set(0,1,0);camera.position.set((state.extent==='inside'?23:26)/2+entryOffset.x,1.75,1.8+entryOffset.z);const dir=new THREE.Vector3(Math.sin(entryYaw)*Math.cos(entryPitch),Math.sin(entryPitch),-Math.cos(entryYaw)*Math.cos(entryPitch));camera.lookAt(camera.position.clone().addScaledVector(dir,15))}else{camera.up.set(0,1,0);camera.position.set(target.x+radius*Math.sin(phi)*Math.sin(theta),radius*Math.cos(phi),target.z+radius*Math.sin(phi)*Math.cos(theta));camera.lookAt(target)}camera.updateMatrixWorld(true);requestEditorRender()}
function view(m){mode=m;for(const id of ['iso','top','entry'])$(id).classList.toggle('active',id===m);updateHint();if(m==='top'){$('roofcheck').checked=false;roofGroup.visible=false;camera.fov=40}else{camera.fov=m==='entry'?75:43}camera.updateProjectionMatrix();cameraUpdate()}
function ground(e){camera.updateMatrixWorld(true);let r=vp.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);let p=new THREE.Vector3();if(!ray.ray.intersectPlane(plane,p))return null;p.z=-p.z;return p}
function hitTable(e){ground(e);model.updateMatrixWorld(true);const meshes=[];tableGroup.traverse(o=>{if(o.isMesh)meshes.push(o)});let hits=ray.intersectObjects(meshes,false);for(const h of hits){let o=h.object;while(o&&o!==tableGroup){if(o.userData.tableId!==undefined)return o.userData.tableId;o=o.parent}}return null}
function download(data,name,mime){let u=URL.createObjectURL(new Blob([data],{type:mime}));let a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
function persist(){try{localStorage.setItem('salon-encanto-maqueta-v1',JSON.stringify(state))}catch(e){}document.dispatchEvent(new CustomEvent('jch:change'))}
function sync(){for(const key of ['extent','stageH','rampL','floorX','floorZ','floorAngle'])$(key).value=state[key]}
const validate=JCHModel.validate;
function glb(){flushTables();return JCHModel.exportGLB(model,state,{roofGroup})}
function hasParent(o,p){while(o){if(o===p)return true;o=o.parent}return false}
try{
renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0xe7e9de);vp.prepend(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(43,1,.1,150);scene.add(new THREE.HemisphereLight(0xf4f5ea,0x79806b,2.5));let light=new THREE.DirectionalLight(0xfff4dd,3);light.position.set(-6,26,10);light.castShadow=true;light.shadow.mapSize.set(2048,2048);light.shadow.camera.left=-25;light.shadow.camera.right=35;light.shadow.camera.top=35;light.shadow.camera.bottom=-25;light.shadow.bias=-.0004;scene.add(light);box(85,.2,85,10,-.5,8,mat(0xe7e9de),scene);
for(const [k,v]of Object.entries(C))materials[k]=mat(v);materials.base=mat(0xc0c6b0);materials.wood=mat(0x9a7052);materials.leaf=mat(0x416035);materials.floor=mat(0xf4f3ea);materials.chair=mat(0xf6f1df);materials.terracotta=mat(0xb66d56);materials.grass=mat(0xffffff,{map:texture('grass')});materials.stone=mat(C.stone,{map:texture('stone')});materials.roof=mat(0xf1f0e8,{side:THREE.DoubleSide});materials.mural=mat(0x6f8a57,{side:THREE.DoubleSide});
try{let raw=localStorage.getItem('salon-encanto-maqueta-v1');if(raw)Object.assign(state,validate(JSON.parse(raw)))}catch(e){}nextId=state.tables.reduce((m,t)=>Math.max(m,t.id+1),1);sync();build();cameraUpdate();new ResizeObserver(()=>{let w=vp.clientWidth,h=vp.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();camera.updateMatrixWorld(true);requestEditorRender()}).observe(vp);requestEditorRender();$('loading').remove();
}catch(e){$('loading').textContent='Este navegador no pudo activar WebGL. Abre el archivo en Chrome o Edge actualizado.';console.error(e);return}
for(const id of ['iso','top','entry'])$(id).onclick=()=>view(id);$('roofcheck').onchange=()=>{roofGroup.visible=$('roofcheck').checked;requestEditorRender()};$('dimcheck').onchange=()=>{dimGroup.visible=$('dimcheck').checked;requestEditorRender()};
$('extent').onchange=()=>{state.extent=$('extent').value;state.floorX+=(state.extent==='outside'?1.5:-1.5);fitFloor();target.x=(state.extent==='inside'?20:23)/2;sync();build();cameraUpdate();persist()};$('apply').onclick=()=>{let proposed={...state};for(const k of ['stageH','rampL'])proposed[k]=Number($(k).value);try{validate(proposed);Object.assign(state,proposed);build();persist()}catch(e){alert(e.message)}};
$('move').onclick=()=>{let t=state.tables.find(t=>t.id===selected);if(!t)return;let x=Number($('tx').value),z=Number($('tz').value);if(!Number.isFinite(x)||!Number.isFinite(z)||x<0||x>23||z<0||z>20)return;t.x=x;t.z=z;updateTables()};$('delete').onclick=()=>{state.tables=state.tables.filter(t=>t.id!==selected);selected=null;updateTables()};
$('save').onclick=()=>{flushTables();download(JSON.stringify(state,null,2),'Salon_Encanto_distribucion.json','application/json')};$('load').onclick=()=>$('file').click();$('file').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>200000)throw Error('Archivo demasiado grande');const loaded=validate(JSON.parse(await f.text()));flushTables();Object.assign(state,loaded);selected=null;tableMode='new';nextId=state.tables.reduce((n,t)=>Math.max(n,t.id+1),1);sync();build();persist();view('top')}catch(e){alert(e.message)}e.target.value=''};
$('png').onclick=()=>{flushTables();renderer.render(scene,camera);renderer.domElement.toBlob(b=>download(b,'Salon_Encanto_render.png','image/png'))};$('glb').onclick=()=>download(glb(),'Salon_Encanto_base.glb','model/gltf-binary');
function normalizeAngle(a){return Math.round(((a%360)+360)%360*100)/100}
function floorBounds(angle){const a=THREE.MathUtils.degToRad(angle);return {x:Math.abs(Math.cos(a))*3.65+Math.abs(Math.sin(a))*2.5,z:Math.abs(Math.sin(a))*3.65+Math.abs(Math.cos(a))*2.5}}
function fitFloor(){const W=state.extent==='inside'?20:23,b=floorBounds(state.floorAngle);state.floorX=THREE.MathUtils.clamp(state.floorX,3+b.x,W-b.x);state.floorZ=THREE.MathUtils.clamp(state.floorZ,b.z,20-b.z)}
function syncFloor(){for(const k of ['floorX','floorZ','floorAngle'])if(document.activeElement!==$(k))$(k).value=Number(state[k].toFixed(2))}
function updateFloorTransform(){for(const group of [floorGroup,floorDims]){group.position.set(state.floorX,0,state.floorZ);group.rotation.y=THREE.MathUtils.degToRad(state.floorAngle);group.updateMatrixWorld(true)}floorSelection.visible=selected==='floor';requestEditorRender()}
function selectFloor(){flushTables();selected='floor';tableMode='new';highlightTables();setNavigation('rotate');updateStatus()}
function turnFloor(delta){state.floorAngle=normalizeAngle(state.floorAngle+delta);fitFloor();selectFloor();updateFloorTransform();sync();persist()}
function hitObject(e){ground(e);model.updateMatrixWorld(true);const meshes=[];for(const group of [tableGroup,floorGroup])group.traverse(o=>{if(o.isMesh)meshes.push(o)});for(const h of ray.intersectObjects(meshes,false)){let o=h.object;while(o&&o!==model){if(o.userData.tableId!==undefined)return o.userData.tableId;if(o.userData.isFloor)return 'floor';o=o.parent}}return null}
function selectTable(id){flushTables();selected=state.tables.some(t=>t.id===id)?id:null;tableMode=selected===null?'new':'single';highlightTables();setNavigation('rotate');updateStatus()}
function setNavigation(value){navMode=value;for(const id of ['rotate','pan']){const active=value===id;$(id).classList.toggle('active',active);$(id).setAttribute('aria-pressed',String(active))}updateHint()}
function updateHint(){$('hint').textContent=mode==='top'?'Arrastra mesas o pista para moverlas · Arrastra el fondo para desplazar la vista':navMode==='pan'?'Arrastra para desplazar la vista · Toca Girar vista para volver a girar':'Arrastra mesas o pista para moverlas · Arrastra el fondo para girar · Dos dedos para mover y acercar'}
function zoomBy(factor){if(!Number.isFinite(factor)||factor<=0)return;if(mode==='top')topDistance=THREE.MathUtils.clamp(topDistance*factor,18,90);else if(mode==='entry')camera.fov=THREE.MathUtils.clamp(camera.fov*factor,35,90);else radius=THREE.MathUtils.clamp(radius*factor,18,75);camera.updateProjectionMatrix();cameraUpdate()}
function panByPixels(dx,dy){camera.updateMatrixWorld(true);const distance=mode==='top'?topDistance:mode==='entry'?12:radius;const step=2*distance*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))/Math.max(1,vp.clientHeight);const right=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0);right.y=0;right.normalize();const up=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,1);up.y=0;up.normalize();const destination=mode==='entry'?entryOffset:target;destination.addScaledVector(right,-dx*step).addScaledVector(up,-dy*step);destination.x=THREE.MathUtils.clamp(destination.x,-25,45);destination.z=THREE.MathUtils.clamp(destination.z,-45,25);cameraUpdate()}
function deleteSelected(){if(selected===null||selected==='floor')return;flushTables();const old=selected;state.tables=state.tables.filter(t=>t.id!==old);selected=null;tableMode='new';tableDrag=null;updateTables();updateHint()}
function gesture(){const p=[...touches.values()];return {distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2}}
const canvas=renderer.domElement;
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&![0,1,2].includes(e.button))return;e.preventDefault();try{canvas.setPointerCapture(e.pointerId)}catch(error){}touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size>=2){pinch=gesture();down=null;tableDrag=null;return}let hit=navMode==='pan'||e.button!==0||e.shiftKey?null:hitObject(e);down={x:e.clientX,y:e.clientY,action:navMode==='pan'||e.button!==0||e.shiftKey||mode==='top'?'pan':'orbit'};if(hit!==null){if(hit==='floor')selectFloor();else selectTable(hit);let p=ground(e),t=hit==='floor'?{x:state.floorX,z:state.floorZ}:state.tables.find(t=>t.id===hit);if(p&&t)tableDrag={id:hit,dx:t.x-p.x,dz:t.z-p.z}}});
canvas.addEventListener('pointermove',e=>{if(!touches.has(e.pointerId))return;e.preventDefault();touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size>=2){const current=gesture();if(pinch){zoomBy(pinch.distance/Math.max(1,current.distance));panByPixels(current.x-pinch.x,current.y-pinch.y)}pinch=current;return}if(tableDrag&&tableDrag.id==='floor'){const p=ground(e);if(p){state.floorX=Math.round((p.x+tableDrag.dx)*10)/10;state.floorZ=Math.round((p.z+tableDrag.dz)*10)/10;fitFloor();updateFloorTransform();updateStatus()}}else if(tableDrag){let p=ground(e),t=state.tables.find(t=>t.id===tableDrag.id);if(p&&t){const W=state.extent==='inside'?20:23;t.x=THREE.MathUtils.clamp(Math.round((p.x+tableDrag.dx)*10)/10,0,W);t.z=THREE.MathUtils.clamp(Math.round((p.z+tableDrag.dz)*10)/10,0,20);const group=tableGroup.children.find(o=>o.userData.tableId===t.id);group.position.set(t.x,0,t.z);group.updateMatrixWorld(true);updateStatus()}}else if(down){const dx=e.clientX-down.x,dy=e.clientY-down.y;if(down.action==='pan')panByPixels(dx,dy);else if(mode==='entry'){entryYaw-=dx*.006;entryPitch=THREE.MathUtils.clamp(entryPitch+dy*.004,-.65,.65);cameraUpdate()}else{theta-=dx*.008;phi=THREE.MathUtils.clamp(phi+dy*.006,.2,1.4);cameraUpdate()}down.x=e.clientX;down.y=e.clientY}});
function release(e){touches.delete(e.pointerId);down=null;tableDrag=null;pinch=null;persist()}
canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',release);
canvas.addEventListener('wheel',e=>{e.preventDefault();zoomBy(Math.exp(THREE.MathUtils.clamp(e.deltaY,-120,120)*.001))},{passive:false});
$('rotate').onclick=()=>setNavigation('rotate');$('pan').onclick=()=>setNavigation('pan');$('quickDelete').onclick=deleteSelected;$('delete').onclick=deleteSelected;$('tableSelect').onchange=()=>selectTable($('tableSelect').value?Number($('tableSelect').value):null);
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.target.isContentEditable)return;if(e.key==='Delete'||e.key==='Backspace'){if(selected!==null&&selected!=='floor'){e.preventDefault();deleteSelected()}}});
$('selectFloor').onclick=selectFloor;$('floorLeft').onclick=$('quickFloorLeft').onclick=()=>turnFloor(-15);$('floorRight').onclick=$('quickFloorRight').onclick=()=>turnFloor(15);$('floor90').onclick=()=>turnFloor(90);
$('applyFloor').onclick=()=>{const proposed={...state,floorX:Number($('floorX').value),floorZ:Number($('floorZ').value),floorAngle:Number($('floorAngle').value)};try{const valid=validate(proposed);flushTables();Object.assign(state,valid);selectFloor();updateFloorTransform();sync();persist()}catch(e){alert(e.message)}};
$('csv').onclick=()=>{flushTables();const rows=[['Mesa','Nombre','Forma','Largo / diámetro (m)','Ancho (m)','Sillas','Separación de sillas (m)','Giro (grados)','X (m)','Fondo (m)'],...state.tables.map(t=>['M'+tableNumber(t),t.label,{round:'Redonda',rectangle:'Rectangular',square:'Cuadrada'}[t.shape],t.w,t.d,t.seats,t.chairGap,t.angle,t.x,t.z])];const quote=v=>{let s=String(v);if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};download('﻿'+rows.map(r=>r.map(quote).join(',')).join('\r\n'),'Salon_Encanto_mesas.csv','text/csv;charset=utf-8')};
bindTableEditor();setNavigation('rotate');
function restoreLayout(value){const loaded=validate(value);flushTables();Object.assign(state,loaded);selected=null;tableMode='new';nextId=state.tables.reduce((n,t)=>Math.max(n,t.id+1),1);sync();build();persist();view('iso')}
function editTablePatch(patch){const targets=tableMode==='new'?[{...newTableDraft,id:1,x:6,z:3}]:editorTargets();try{const proposed=targets.map(t=>normalizeTable({...t,...patch}));if(tableMode==='new')newTableDraft={...proposed[0]};else{targets.forEach((t,i)=>Object.assign(t,proposed[i]));queueTables(targets.map(t=>t.id));persist()}tableError();updateStatus();return true}catch(e){tableError(e.message);return false}}
window.encanto={state,editTablePatch,editorTargets,get draft(){return newTableDraft},tableNumber,updateTables,restore:restoreLayout,persist,selectTable,chairLayout,tableFootprint,normalizeTable,flushTables,get tableGroup(){return tableGroup},get tableMode(){return tableMode},get model(){return model},get camera(){return camera},get renderer(){return renderer},view,build,glb,validate,collision,get mode(){return mode},get selected(){return selected},hitTable,hitObject,ground,get floorGroup(){return floorGroup},get roofGroup(){return roofGroup},get dimGroup(){return dimGroup},floorBounds,render:()=>renderer.render(scene,camera)};
})();
