(()=>{'use strict';
const $=id=>document.getElementById(id),engine=window.encanto;if(!engine)return;
const META_KEY='jch3d-event-meta-v1',EVENTS_KEY='jch3d-events-v1';
let dragging=false;
let meta={title:'Distribución sin título',date:'',settings:{...JCHShare.defaults}},frozen=null,shareGeneration=0,history=[],cursor=-1,restoring=false,saveTimer=0;
try{const saved=JSON.parse(localStorage.getItem(META_KEY));if(saved&&typeof saved.title==='string')meta={title:saved.title.slice(0,100),date:typeof saved.date==='string'?saved.date:'',settings:JCHShare.settings(saved.settings)}}catch{}
function message(text){$('appToast').textContent=text;$('appToast').hidden=false;clearTimeout(saveTimer);saveTimer=setTimeout(()=>$('appToast').hidden=true,4000)}
function writeMeta(){try{localStorage.setItem(META_KEY,JSON.stringify(meta))}catch{message('No se pudo guardar en este dispositivo. Descarga el JSON para conservarlo.')}$('eventTitle').textContent=meta.title||'Distribución sin título';$('eventSubtitle').textContent=meta.date?meta.date+' · Salón Encanto':'Salón Encanto · Diseño de evento'}
function presentation(){engine.flushTables();return {version:1,venue:'encanto',title:meta.title||'Salón Encanto',date:meta.date,layout:structuredClone(engine.state),settings:JCHShare.settings(meta.settings)}}
function dialog(id){$(id).showModal()}
function close(id){$(id).close()}
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>close(b.dataset.close);
for(const d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});
function busy(button,task){return async()=>{button.disabled=true;const text=button.textContent;button.textContent='Preparando…';try{await task()}catch(e){message(e.message)}finally{button.disabled=false;button.textContent=text}}}
$('eventEdit').onclick=()=>{$('eventNameInput').value=meta.title;$('eventDateInput').value=meta.date;dialog('eventDialog')};
$('eventForm').onsubmit=e=>{e.preventDefault();meta.title=$('eventNameInput').value.trim()||'Distribución sin título';meta.date=$('eventDateInput').value;writeMeta();close('eventDialog')};
function updateSummary(){const n=engine.state.tables.length,s=engine.state.tables.reduce((a,t)=>a+t.seats,0);$('tableCount').textContent=n;$('seatCount').textContent=s;$('eventTitle').title=meta.title}
function record(){if(restoring||dragging)return;const value=JSON.stringify(engine.state);if(history[cursor]===value)return;history=history.slice(0,cursor+1);history.push(value);if(history.length>80)history.shift();cursor=history.length-1;syncHistory();updateSummary()}
function syncHistory(){$('undo').disabled=cursor<1;$('redo').disabled=cursor>=history.length-1}
function jump(delta){if(delta<0){dragging=false;record()}if(cursor+delta<0||cursor+delta>=history.length)return;restoring=true;cursor+=delta;engine.restore(JSON.parse(history[cursor]));restoring=false;syncHistory();updateSummary()}
$('undo').onclick=()=>jump(-1);$('redo').onclick=()=>jump(1);
engine.renderer.domElement.addEventListener('pointerdown',()=>dragging=true);for(const event of ['pointerup','pointercancel','lostpointercapture'])document.addEventListener(event,()=>{dragging=false;queueMicrotask(record)},{capture:true});document.addEventListener('jch:change',record);
const observer=new MutationObserver(updateSummary);observer.observe($('status'),{childList:true,characterData:true,subtree:true});record();
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();jump(e.shiftKey?1:-1)}});
async function exportHTML(p=presentation()){await JCHModel.assetsReady;const venue=JCHModel.createVenue(p.layout);try{await JCHShare.downloadViewer(new Uint8Array(venue.glb()),p)}finally{venue.dispose()}}
$('offlineHTML').onclick=busy($('offlineHTML'),()=>exportHTML());
$('glb').onclick=busy($('glb'),async()=>{await JCHModel.assetsReady;const p=presentation(),venue=JCHModel.createVenue(p.layout);try{JCHShare.save(venue.glb(),JCHShare.filename(meta.title)+'.glb','model/gltf-binary')}finally{venue.dispose()}});
$('shareOpen').onclick=async()=>{frozen=presentation();const generation=++shareGeneration;$('shareURL').value='';$('shareURL').placeholder='Generando enlace…';$('shareError').textContent='';$('shareCopy').disabled=true;$('shareNative').disabled=true;$('shareView').removeAttribute('href');$('shareHeading').textContent=frozen.title;for(const [k,v]of Object.entries(frozen.settings)){const e=$('share-'+k);if(e){if(e.type==='checkbox')e.checked=v;else e.value=v}}dialog('shareDialog');await regenerate(generation)};
async function regenerate(generation=++shareGeneration){if(!frozen)return;frozen.settings=JCHShare.settings(meta.settings);try{const url=await JCHShare.link(frozen);if(generation!==shareGeneration)return;$('shareURL').value=url;$('shareView').href=url;$('shareCopy').disabled=false;$('shareNative').disabled=false;$('shareError').textContent=''}catch(e){if(generation===shareGeneration){$('shareError').textContent=e.message;$('shareCopy').disabled=true;$('shareNative').disabled=true;$('shareView').removeAttribute('href')}}}
for(const k of Object.keys(JCHShare.defaults)){const e=$('share-'+k);if(e)e.onchange=async()=>{meta.settings[k]=e.type==='checkbox'?e.checked:e.type==='range'?Number(e.value):e.value;writeMeta();await regenerate()}}
$('shareView').onclick=e=>{if(!$('shareView').href)e.preventDefault()};
$('shareCopy').onclick=busy($('shareCopy'),async()=>{const url=$('shareURL').value;if(!url)throw Error('El enlace todavía no está listo');try{await navigator.clipboard.writeText(url);$('shareCopyState').textContent='Enlace copiado';message('Enlace copiado')}catch{$('shareURL').focus();$('shareURL').select();if(document.execCommand('copy')){$('shareCopyState').textContent='Enlace copiado';message('Enlace copiado')}else{$('shareCopyState').textContent='Mantén pulsado el enlace y elige Copiar';message('Selecciona y copia el enlace')}}});
$('shareNative').onclick=busy($('shareNative'),async()=>{const data={title:frozen.title,text:'Explora nuestra propuesta en 3D',url:$('shareURL').value};if(!data.url)throw Error('El enlace todavía no está listo');if(navigator.share){try{await navigator.share(data)}catch(e){if(e.name!=='AbortError')throw e}}else{$('shareCopy').click()}});
$('shareHTML').onclick=busy($('shareHTML'),()=>exportHTML(frozen));
$('preview').onclick=async()=>{const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;try{const href=await JCHShare.link(presentation());if(tab)tab.location.href=href;else{message('Permite las ventanas emergentes o usa Compartir → Abrir presentación');$('shareOpen').click()}}catch(e){tab?.close();message(e.message)}};
function events(){try{const rows=JSON.parse(localStorage.getItem(EVENTS_KEY)||'[]');return Array.isArray(rows)?rows.filter(r=>r&&typeof r.id==='string'&&r.presentation).slice(0,40):[]}catch{return []}}
function putEvents(rows){localStorage.setItem(EVENTS_KEY,JSON.stringify(rows))}
function renderEvents(){const list=$('eventsList');list.replaceChildren();const rows=events();if(!rows.length){const p=document.createElement('p');p.className='note';p.textContent='Aquí aparecerán los eventos que guardes en este dispositivo.';list.append(p)}for(const r of rows){const card=document.createElement('article');card.className='event-card';const title=document.createElement('strong');title.textContent=r.presentation.title;const info=document.createElement('p');info.textContent=(r.presentation.date?r.presentation.date+' · ':'')+(r.presentation.layout?.tables.length||0)+' mesas';const open=document.createElement('button');open.textContent='Abrir';open.onclick=()=>{try{const p=JCHShare.validatePresentation(r.presentation);engine.restore(p.layout);meta={title:p.title,date:p.date,settings:p.settings};writeMeta();window.JCHEvents?.restore(r.administration||{});record();close('eventsDialog');message('Evento abierto')}catch(e){message(e.message)}};const remove=document.createElement('button');remove.textContent='Eliminar';remove.className='small subtle';remove.onclick=()=>{if(confirm('¿Eliminar este evento guardado? La distribución abierta se conserva.')){try{putEvents(events().filter(x=>x.id!==r.id));renderEvents()}catch(e){message('No se pudo eliminar el evento')}}};const buttons=document.createElement('div');buttons.className='actions';buttons.append(open,remove);card.append(title,info,buttons);list.append(card)}}
$('eventsOpen').onclick=()=>{renderEvents();dialog('eventsDialog')};
$('eventSave').onclick=()=>{try{const rows=events();if(rows.length>=40)throw Error('Puedes conservar hasta 40 eventos en este dispositivo. Exporta los que quieras archivar.');rows.unshift({id:crypto.randomUUID(),savedAt:new Date().toISOString(),presentation:presentation(),administration:window.JCHEvents?.data()||{}});putEvents(rows);message('Evento guardado en este dispositivo')}catch(e){message(e.message)}};
$('newEvent').onclick=()=>{if(engine.state.tables.length&&!confirm('¿Empezar una distribución vacía? Guarda o descarga la actual si quieres conservarla.'))return;engine.restore(JCHModel.defaultLayout());meta={title:'Distribución sin título',date:'',settings:{...JCHShare.defaults}};writeMeta();window.JCHEvents?.restore({});record();message('Nueva distribución lista')};
$('loadProposal').onclick=busy($('loadProposal'),async()=>{if(engine.state.tables.length&&!confirm('¿Abrir tu propuesta de referencia? Guarda la distribución actual si quieres conservarla.'))return;const r=await fetch('/assets/models/encanto-propuesta.json');if(!r.ok)throw Error('No se pudo abrir la propuesta');engine.restore(await r.json());window.JCHEvents?.restore({});meta.title='Propuesta Salón Encanto';writeMeta();record();message('Propuesta abierta: 23 mesas y 226 sillas')});
$('zoomInEditor').onclick=()=>{engine.renderer.domElement.dispatchEvent(new WheelEvent('wheel',{deltaY:-120,bubbles:true,cancelable:true}))};
$('zoomOutEditor').onclick=()=>{engine.renderer.domElement.dispatchEvent(new WheelEvent('wheel',{deltaY:120,bubbles:true,cancelable:true}))};
$('fullscreenEditor').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else document.body.classList.toggle('focus-mode')}catch{document.body.classList.toggle('focus-mode')}};
writeMeta();updateSummary();window.JCHStudio={presentation,exportHTML,history:()=>({count:history.length,cursor}),meta:()=>structuredClone(meta),message,setMeta:value=>{meta={title:typeof value.title==='string'?value.title.slice(0,100):'Distribución sin título',date:typeof value.date==='string'?value.date:'',settings:JCHShare.settings(value.settings)};writeMeta()}};
})();
