(()=>{'use strict';
const $=id=>document.getElementById(id),engine=window.encanto;if(!engine)return;
const metaKey=()=>engine.state.venue==='encanto'?'jch3d-event-meta-v1':'jch3d-event-meta-espejos-v1',EVENTS_KEY='jch3d-events-v1';
let dragging=false;
let meta={title:'Distribución sin título',date:'',settings:{...JCHShare.defaults}},frozen=null,shareGeneration=0,history=[],cursor=-1,restoring=false,saveTimer=0;
try{const saved=JSON.parse(localStorage.getItem(metaKey()));if(saved&&typeof saved.title==='string')meta={title:saved.title.slice(0,100),date:typeof saved.date==='string'?saved.date:'',settings:JCHShare.settings(saved.settings)}}catch{}
function message(text){$('appToast').textContent=text;$('appToast').hidden=false;clearTimeout(saveTimer);saveTimer=setTimeout(()=>$('appToast').hidden=true,4000)}
function writeMeta(){try{localStorage.setItem(metaKey(),JSON.stringify(meta))}catch{message('No se pudo guardar en este dispositivo. Descarga el JSON para conservarlo.')}$('eventTitle').textContent=meta.title||'Distribución sin título';$('eventSubtitle').textContent=meta.date?meta.date+' · '+JCHVenues.names[engine.state.venue]:JCHVenues.names[engine.state.venue]+' · Diseño de evento'}
function presentation(){engine.flushTables();return {version:1,venue:engine.state.venue,title:meta.title||JCHVenues.names[engine.state.venue],date:meta.date,layout:structuredClone(engine.state),settings:JCHShare.settings(meta.settings)}}
function dialog(id){$(id).showModal()}
function close(id){$(id).close()}
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>close(b.dataset.close);
for(const d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});
function busy(button,task){return async()=>{button.disabled=true;const text=button.textContent;button.textContent='Preparando…';try{await task()}catch(e){message(e.message)}finally{button.disabled=false;button.textContent=text}}}
$('eventEdit').onclick=()=>{$('eventNameInput').value=meta.title;$('eventDateInput').value=meta.date;dialog('eventDialog')};
$('eventForm').onsubmit=e=>{e.preventDefault();meta.title=$('eventNameInput').value.trim()||'Distribución sin título';meta.date=$('eventDateInput').value;writeMeta();close('eventDialog')};
function updateSummary(){const n=engine.state.tables.length,s=engine.state.tables.reduce((a,t)=>a+t.seats,0);$('tableCount').textContent=n;$('seatCount').textContent=s;$('eventTitle').title=meta.title}
function record(){if(restoring||dragging)return;const value=JSON.stringify(engine.state);if(history[cursor]===value)return;history=history.slice(0,cursor+1);history.push(value);if(history.length>80)history.shift();cursor=history.length-1;syncHistory();updateSummary()}
function syncHistory(){$('undo').disabled=cursor<1;$('redo').disabled=cursor>=history.length-1}
function jump(delta){if(delta<0){dragging=false;record()}if(cursor+delta<0||cursor+delta>=history.length)return;restoring=true;cursor+=delta;engine.restore(JSON.parse(history[cursor]));restoring=false;syncHistory();updateSummary()}
$('undo').onclick=()=>jump(-1);$('redo').onclick=()=>jump(1);
engine.renderer.domElement.addEventListener('pointerdown',()=>dragging=true);for(const event of ['pointerup','pointercancel','lostpointercapture'])document.addEventListener(event,()=>{dragging=false;queueMicrotask(record)},{capture:true});document.addEventListener('jch:change',()=>{record();if(engine.state.venue==='espejos')for(const k of ['hallW','hallD','floorW','floorD'])if(document.activeElement!==$(k))$(k).value=engine.state[k]});
const observer=new MutationObserver(updateSummary);observer.observe($('status'),{childList:true,characterData:true,subtree:true});record();
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();jump(e.shiftKey?1:-1)}});
async function exportHTML(p=presentation()){await JCHModel.ready(p.layout.venue);const venue=JCHModel.createVenue(p.layout);try{await JCHShare.downloadViewer(new Uint8Array(venue.glb()),p)}finally{venue.dispose()}}
$('offlineHTML').onclick=busy($('offlineHTML'),()=>exportHTML());
$('glb').onclick=busy($('glb'),async()=>{const p=presentation();await JCHModel.ready(p.layout.venue);const venue=JCHModel.createVenue(p.layout);try{JCHShare.save(venue.glb(),JCHShare.filename(meta.title)+'.glb','model/gltf-binary')}finally{venue.dispose()}});
$('shareOpen').onclick=async()=>{frozen=presentation();const generation=++shareGeneration;$('shareURL').value='';$('shareURL').placeholder='Generando enlace…';$('shareError').textContent='';$('shareCopy').disabled=true;$('shareNative').disabled=true;$('shareView').removeAttribute('href');$('shareHeading').textContent=frozen.title;for(const [k,v]of Object.entries(frozen.settings)){const e=$('share-'+k);if(e){if(e.type==='checkbox')e.checked=v;else e.value=v}}dialog('shareDialog');await regenerate(generation)};
async function regenerate(generation=++shareGeneration){if(!frozen)return;frozen.settings=JCHShare.settings(meta.settings);try{const url=await JCHShare.link(frozen);if(generation!==shareGeneration)return;$('shareURL').value=url;$('shareView').href=url;$('shareCopy').disabled=false;$('shareNative').disabled=false;$('shareError').textContent=''}catch(e){if(generation===shareGeneration){$('shareError').textContent=e.message;$('shareCopy').disabled=true;$('shareNative').disabled=true;$('shareView').removeAttribute('href')}}}
for(const k of Object.keys(JCHShare.defaults)){const e=$('share-'+k);if(e)e.onchange=async()=>{meta.settings[k]=e.type==='checkbox'?e.checked:e.type==='range'?Number(e.value):e.value;writeMeta();await regenerate()}}
$('shareView').onclick=e=>{if(!$('shareView').href)e.preventDefault()};
$('shareCopy').onclick=busy($('shareCopy'),async()=>{const url=$('shareURL').value;if(!url)throw Error('El enlace todavía no está listo');try{await navigator.clipboard.writeText(url);$('shareCopyState').textContent='Enlace copiado';message('Enlace copiado')}catch{$('shareURL').focus();$('shareURL').select();if(document.execCommand('copy')){$('shareCopyState').textContent='Enlace copiado';message('Enlace copiado')}else{$('shareCopyState').textContent='Mantén pulsado el enlace y elige Copiar';message('Selecciona y copia el enlace')}}});
$('shareNative').onclick=busy($('shareNative'),async()=>{const data={title:frozen.title,text:'Explora nuestra propuesta en 3D',url:$('shareURL').value};if(!data.url)throw Error('El enlace todavía no está listo');if(navigator.share){try{await navigator.share(data)}catch(e){if(e.name!=='AbortError')throw e}}else{$('shareCopy').click()}});
$('shareHTML').onclick=busy($('shareHTML'),()=>exportHTML(frozen));
$('preview').onclick=async()=>{const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;try{const href=await JCHShare.link(presentation());if(tab)tab.location.href=href;else{message('Permite las ventanas emergentes o usa Compartir → Abrir presentación');$('shareOpen').click()}}catch(e){tab?.close();message(e.message)}};
function events(){try{const rows=JSON.parse(localStorage.getItem(EVENTS_KEY)||'[]');return Array.isArray(rows)?rows.filter(r=>r&&typeof r.id==='string'&&r.presentation).slice(0,40):[]}catch{return []}}
function putEvents(rows){localStorage.setItem(EVENTS_KEY,JSON.stringify(rows))}
function renderEvents(){const list=$('eventsList');list.replaceChildren();const rows=events();if(!rows.length){const p=document.createElement('p');p.className='note';p.textContent='Aquí aparecerán los eventos que guardes en este dispositivo.';list.append(p)}for(const r of rows){const card=document.createElement('article');card.className='event-card';const title=document.createElement('strong');title.textContent=r.presentation.title;const info=document.createElement('p');info.textContent=(r.presentation.date?r.presentation.date+' · ':'')+JCHVenues.names[r.presentation.venue||'encanto']+' · '+(r.presentation.layout?.tables.length||0)+' mesas';const open=document.createElement('button');open.textContent='Abrir';open.onclick=()=>{try{const p=JCHShare.validatePresentation(r.presentation);engine.restore(p.layout);meta={title:p.title,date:p.date,settings:p.settings};writeMeta();window.JCHEvents?.restore(r.administration||{});record();close('eventsDialog');message('Evento abierto')}catch(e){message(e.message)}};const remove=document.createElement('button');remove.textContent='Eliminar';remove.className='small subtle';remove.onclick=()=>{if(confirm('¿Eliminar este evento guardado? La distribución abierta se conserva.')){try{putEvents(events().filter(x=>x.id!==r.id));renderEvents()}catch(e){message('No se pudo eliminar el evento')}}};const buttons=document.createElement('div');buttons.className='actions';buttons.append(open,remove);card.append(title,info,buttons);list.append(card)}}
$('eventsOpen').onclick=()=>{renderEvents();dialog('eventsDialog')};
$('eventSave').onclick=()=>{try{const rows=events();if(rows.length>=40)throw Error('Puedes conservar hasta 40 eventos en este dispositivo. Exporta los que quieras archivar.');rows.unshift({id:crypto.randomUUID(),savedAt:new Date().toISOString(),presentation:presentation(),administration:window.JCHEvents?.data()||{}});putEvents(rows);message('Evento guardado en este dispositivo')}catch(e){message(e.message)}};
$('newEvent').onclick=()=>{if(engine.state.tables.length&&!confirm('¿Empezar una distribución vacía? Guarda o descarga la actual si quieres conservarla.'))return;engine.restore(JCHModel.defaultLayout(engine.state.venue));meta={title:'Distribución sin título',date:'',settings:{...JCHShare.defaults}};writeMeta();window.JCHEvents?.restore({});record();message('Nueva distribución lista')};
$('loadProposal').onclick=busy($('loadProposal'),async()=>{if(engine.state.tables.length&&!confirm('¿Abrir el montaje de referencia? Guarda la distribución actual si quieres conservararla.'))return;const name=engine.state.venue,r=await fetch('/assets/models/'+name+'-propuesta.json');if(!r.ok)throw Error('No se pudo abrir la propuesta');engine.restore(await r.json());window.JCHEvents?.restore({});meta.title='Propuesta '+JCHVenues.names[name];writeMeta();record();message('Propuesta abierta: '+engine.state.tables.length+' mesas y '+engine.state.tables.reduce((n,t)=>n+t.seats,0)+' sillas')});
function syncVenue(){
 const is=engine.state.venue==='espejos',m=engine.metrics();$('venueSelect').value=engine.state.venue;$('venueName').textContent=JCHVenues.names[engine.state.venue];$('extentField').hidden=is;$('encantoMeasures').hidden=is;$('espejosMeasures').hidden=!is;
 $('venueDetails').innerHTML=is?'Loseta clara y pista de madera en nivel inferior<br>Espejos a la derecha · Ventanales a la izquierda<br><strong>Dimensiones estimadas · Ajustables</strong>':'Pista: <strong>7.30 × 5.00 m</strong><br>Escenario izquierdo: <strong>20.00 × 3.00 m</strong><br>Entrada al frente · Fondo al lado opuesto';
 $('venueNote').textContent=is?'Reconstrucción visual de las fotografías del sitio. Largo, ancho, alturas y posiciones necesitan medidas del lugar para un montaje a escala exacta.':'Las medidas principales son las indicadas. Posiciones, alturas, rampa, cubierta y arco son aproximaciones de las fotografías. Revisa esas medidas antes del montaje.';
 $('floorNote').textContent=is?'La pista representa el área de madera observada. Puedes ajustar sus medidas, moverla y girarla para probar propuestas. Revisa los desniveles del lugar antes del montaje.':'Toca la pista y arrástrala en 3D o Planta. Gírala con los botones o escribe un ángulo. Sus medidas se conservan y permanece dentro del pasto.';
 $('venueLegend').innerHTML=is?'<span><b style="background:#e8e7df"></b>Loseta elevada</span><span><b style="background:#b98350"></b>Madera</span><span><b style="background:#bcd0ce"></b>Espejos</span><span><b style="background:#54504f"></b>Alfombra / escenario</span>':'<span><b style="background:#567a37"></b>Pasto</span><span><b style="background:#b67b5a"></b>Escenario elevado</span><span><b style="background:#dbdcd5"></b>Pista</span><span><b style="background:#b52437"></b>Acceso trajinera</span>';
 for(const k of ['hallW','hallD','floorW','floorD'])$(k).value=engine.state[k]??(k==='hallW'?20:k==='hallD'?20:k==='floorW'?7.3:5);
 $('tx').max=m.W;$('tz').max=m.D;$('floorX').max=m.W;$('floorZ').max=m.D;$('referenceDescription').textContent=is?'Montaje de ejemplo de Espejos con mesas Tiffany. Medidas por confirmar.':'Tu montaje terminado: 23 mesas y 226 sillas.';$('referenceView').href='/presentacion/'+(is?'?salon=espejos':'');$('venueMeasureError').textContent='';writeMeta();
}
function loadMeta(){meta={title:'Distribución sin título',date:'',settings:{...JCHShare.defaults}};try{const raw=JSON.parse(localStorage.getItem(metaKey()));if(raw)meta={title:typeof raw.title==='string'?raw.title.slice(0,100):meta.title,date:typeof raw.date==='string'?raw.date:'',settings:JCHShare.settings(raw.settings)}}catch{}}
document.addEventListener('jch:venue-before',()=>{writeMeta();window.JCHEvents?.saveCurrent()});
document.addEventListener('jch:venue',()=>{loadMeta();window.JCHEvents?.loadCurrent();history=[];cursor=-1;syncHistory();syncVenue();updateSummary()});
document.addEventListener('jch:asset-error',e=>message(e.detail));
$('venueSelect').onchange=()=>{const name=$('venueSelect').value;try{let value=JCHModel.defaultLayout(name);try{const raw=localStorage.getItem('jch3d-layout-'+name+'-v1')||(name==='encanto'?localStorage.getItem('salon-encanto-maqueta-v1'):null);if(raw){const parsed=engine.validate(JSON.parse(raw));if(parsed.venue===name)value=parsed}}catch{message('No se pudo recuperar el guardado. Abre tu respaldo JSON.')}engine.restore(value);syncVenue();message(JCHVenues.names[name]+' · Distribución recuperada')}catch(e){$('venueSelect').value=engine.state.venue;message(e.message)}};
$('applyVenue').onclick=()=>{try{const proposed={...engine.state};for(const k of ['hallW','hallD','floorW','floorD']){proposed[k]=Number($(k).value);if(!Number.isFinite(proposed[k])||proposed[k]<Number($(k).min)||proposed[k]>Number($(k).max))throw Error('Medida no válida: '+k)}const m=JCHVenues.metrics(proposed),b=JCHModel.floorBounds(proposed.floorAngle,proposed);if(b.x*2>m.W||b.z*2>m.D)throw Error('La pista girada no cabe en esas dimensiones');proposed.floorX=Math.max(b.x,Math.min(m.W-b.x,proposed.floorX));proposed.floorZ=Math.max(b.z,Math.min(m.D-b.z,proposed.floorZ));engine.restore(proposed);syncVenue();message('Medidas actualizadas')}catch(e){$('venueMeasureError').textContent=e.message}};
$('zoomInEditor').onclick=()=>{engine.renderer.domElement.dispatchEvent(new WheelEvent('wheel',{deltaY:-120,bubbles:true,cancelable:true}))};
$('zoomOutEditor').onclick=()=>{engine.renderer.domElement.dispatchEvent(new WheelEvent('wheel',{deltaY:120,bubbles:true,cancelable:true}))};
$('fullscreenEditor').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else document.body.classList.toggle('focus-mode')}catch{document.body.classList.toggle('focus-mode')}};
syncVenue();writeMeta();updateSummary();window.JCHStudio={presentation,exportHTML,history:()=>({count:history.length,cursor}),meta:()=>structuredClone(meta),message,setMeta:value=>{meta={title:typeof value.title==='string'?value.title.slice(0,100):'Distribución sin título',date:typeof value.date==='string'?value.date:'',settings:JCHShare.settings(value.settings)};writeMeta()}};
})();
