(()=>{'use strict';
const $=id=>document.getElementById(id),engine=window.encanto,studio=window.JCHStudio;
const KEYS=['front','right','back','left'],SIDES=['Frente (+ fondo)','Derecha (+ X)','Atrás (− fondo)','Izquierda (− X)'];
let chairIndex=0,chairSync=false;
function current(){return engine.tableMode==='new'?engine.draft:engine.editorTargets()[0]}
function patch(p){return engine.editTablePatch(p)}
function syncChairs(){if(chairSync)return;chairSync=true;const t=current(),all=engine.tableMode==='all';$('chairPlacement').hidden=!t;if(!t){chairSync=false;return}const mode=t.chairMode||'auto';$('chairMode').value=mode;$('chairSides').hidden=mode!=='sides'||t.shape==='round';$('chairArc').hidden=t.shape!=='round';$('manualChairTools').hidden=all||mode!=='manual';$('chairManual').disabled=all||!t.seats;$('chairPlacementNote').textContent=all?'El patrón se aplica a todas las mesas. Para mover una silla individual, selecciona una mesa.':mode==='manual'?'Las posiciones manuales son relativas al centro de la mesa. Girar la mesa también gira sus sillas. Para volver a seguir sus medidas, elige un patrón automático.':'Los lados se miden desde la propia mesa. Las sillas siguen su tamaño, separación y giro.';KEYS.forEach((k,i)=>{if(document.activeElement!==$('side-'+k))$('side-'+k).value=t.chairSides?.[i]||0});for(const k of ['chairArcStart','chairArcSpan'])if(document.activeElement!==$(k))$(k).value=t[k]??(k==='chairArcSpan'?360:0);
const positions=engine.chairLayout(t);chairIndex=Math.min(chairIndex,Math.max(0,positions.length-1));const select=$('chairSelect');select.replaceChildren(...positions.map((p,i)=>new Option('Silla '+(i+1),String(i))));select.value=String(chairIndex);const pos=positions[chairIndex];if(pos){for(const [id,key] of [['chairLocalX','x'],['chairLocalZ','z'],['chairLocalAngle','angle']]){const v=key==='angle'?((pos.angle*180/Math.PI)%360+360)%360:pos[key];for(const el of [$(id),$(id+'Range')])if(document.activeElement!==el)el.value=Math.round(v*100)/100}}
const svg=$('seatingDiagram'),ns='http://www.w3.org/2000/svg';svg.replaceChildren();function add(tag,attributes){const el=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attributes))el.setAttribute(k,String(v));svg.append(el);return el}
const radius=Math.max(2,t.w/2+.7,t.d/2+.7,...positions.map(p=>Math.max(Math.abs(p.x),Math.abs(p.z))+.4));svg.setAttribute('viewBox',[-radius,-radius,2*radius,2*radius].join(' '));add(t.shape==='round'?'circle':'rect',t.shape==='round'?{cx:0,cy:0,r:t.w/2,fill:t.tableColor||'#f4eee1',stroke:'#51715a','stroke-width':.04}:{x:-t.w/2,y:-t.d/2,width:t.w,height:t.d,rx:.06,fill:t.tableColor||'#f4eee1',stroke:'#51715a','stroke-width':.04});positions.forEach((p,i)=>{const circle=add('circle',{cx:p.x,cy:p.z,r:.18,fill:i===chairIndex?'#bda15f':'#305a44','data-chair':i,tabindex:0,role:'button','aria-label':'Seleccionar silla '+(i+1)});circle.onclick=()=>{chairIndex=i;if(!all&&mode!=='manual')makeManual();syncChairs()};circle.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();circle.onclick()}};const text=add('text',{x:p.x,y:p.z+.07,'font-size':.2,'text-anchor':'middle',fill:'white','pointer-events':'none'});text.textContent=i+1});const text=add('text',{x:0,y:radius-.08,'font-size':.18,'text-anchor':'middle',fill:'#587361'});text.textContent='FRENTE (+ fondo)';chairSync=false}
function makeManual(){const t=current();if(!t||engine.tableMode==='all')return;patch({chairMode:'manual',customChairs:engine.chairLayout(t).map(p=>({x:p.x,z:p.z,angle:((p.angle*180/Math.PI)%360+360)%360}))})}
$('chairMode').onchange=()=>{if($('chairMode').value==='manual')makeManual();else patch({chairMode:$('chairMode').value})};$('chairManual').onclick=makeManual;$('chairAuto').onclick=()=>patch({chairMode:'auto',customChairs:[]});KEYS.forEach(k=>$('side-'+k).onchange=()=>patch({chairMode:'sides',chairSides:KEYS.map(k=>Number($('side-'+k).value))}));for(const k of ['chairArcStart','chairArcSpan'])$(k).oninput=()=>patch({[k]:Number($(k).value)});$('chairSelect').onchange=()=>{chairIndex=Number($('chairSelect').value);syncChairs()};
for(const [id,key]of [['chairLocalX','x'],['chairLocalZ','z'],['chairLocalAngle','angle']])for(const el of [$(id),$(id+'Range')])el.oninput=()=>{const t=current();if(!t||engine.tableMode==='all')return;const points=engine.chairLayout(t).map(p=>({x:p.x,z:p.z,angle:((p.angle*180/Math.PI)%360+360)%360}));if(!points[chairIndex])return;points[chairIndex][key]=Number(el.value);patch({chairMode:'manual',customChairs:points})};
document.addEventListener('jch:selection',syncChairs);document.addEventListener('jch:change',syncChairs);syncChairs();
// Private operational information is kept separate from client presentation snapshots.
const STORAGE='jch3d-administration-v1';let data={guests:[],tasks:[],expenses:[],notes:'',expected:0};
function clean(value={}){const str=(v,n)=>typeof v==='string'?v.slice(0,n):'',num=(v,max)=>typeof v==='number'&&Number.isFinite(v)?Math.max(0,Math.min(max,v)):0;return {guests:(Array.isArray(value.guests)?value.guests:[]).slice(0,2000).filter(g=>g&&typeof g.id==='string').map(g=>({id:str(g.id,80),name:str(g.name,100),group:str(g.group,80),notes:str(g.notes,300),tableId:Number.isSafeInteger(g.tableId)?g.tableId:null,status:['pending','confirmed','declined'].includes(g.status)?g.status:'pending'})),tasks:(Array.isArray(value.tasks)?value.tasks:[]).slice(0,200).filter(t=>t&&typeof t.id==='string').map(t=>({id:str(t.id,80),title:str(t.title,150),time:/^\d{2}:\d{2}$/.test(t.time)?t.time:'',done:!!t.done})),expenses:(Array.isArray(value.expenses)?value.expenses:[]).slice(0,200).filter(e=>e&&typeof e.id==='string').map(e=>({id:str(e.id,80),title:str(e.title,100),amount:num(e.amount,100000000),paid:!!e.paid})),notes:str(value.notes,10000),expected:Math.round(num(value.expected,2000))}}
try{data=clean(JSON.parse(localStorage.getItem(STORAGE)||'{}'))}catch{}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(data))}catch{studio.message('Descarga el respaldo del evento para conservar la información.')}renderSummary()}
function restore(value){data=clean(value);save();renderAll()}
function tableName(t){return 'M'+engine.tableNumber(t)+(t.label?' · '+t.label:'')}
function active(){return data.guests.filter(g=>g.status!=='declined')}
function summary(){const guests=active(),tables=engine.state.tables,ids=new Set(tables.map(t=>t.id)),assigned=guests.filter(g=>ids.has(g.tableId)).length;return {total:data.guests.length,confirmed:data.guests.filter(g=>g.status==='confirmed').length,assigned,unassigned:guests.length-assigned,capacity:tables.reduce((a,t)=>a+t.seats,0),overfull:tables.filter(t=>guests.filter(g=>g.tableId===t.id).length>t.seats).map(t=>engine.tableNumber(t))}}
function renderSummary(){const s=summary();$('eventCapacity').textContent=s.capacity+' lugares · '+s.assigned+' asignados · '+s.unassigned+' sin mesa';$('guestSummary').textContent=s.total+' invitados · '+s.confirmed+' confirmados · '+s.unassigned+' sin asignación'+(s.overfull.length?' · Exceso en M'+s.overfull.join(', M'):'');$('guestSummary').classList.toggle('warning',!!s.overfull.length);$('budgetSummary').textContent=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(data.expenses.reduce((a,e)=>a+e.amount,0))+' total · '+new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(data.expenses.filter(e=>!e.paid).reduce((a,e)=>a+e.amount,0))+' pendiente';const done=data.tasks.filter(t=>t.done).length;$('taskSummary').textContent=done+' de '+data.tasks.length+' actividades completadas'}
function button(text,action){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=action;return b}
function tableOptions(select,id){select.replaceChildren(new Option('Sin mesa',''),...engine.state.tables.map(t=>new Option(tableName(t),t.id)));select.value=engine.state.tables.some(t=>t.id===id)?String(id):''}
function renderGuests(){const host=$('guestRows'),q=$('guestSearch').value.trim().toLocaleLowerCase();host.replaceChildren();const guests=data.guests.filter(g=>(g.name+' '+g.group).toLocaleLowerCase().includes(q));for(const g of guests.slice(0,200)){const row=document.createElement('div');row.className='guest-row';const info=document.createElement('div'),name=document.createElement('strong'),note=document.createElement('small');name.textContent=g.name;note.textContent=[g.group,g.notes].filter(Boolean).join(' · ');info.append(name,note);const table=document.createElement('select');table.setAttribute('aria-label','Mesa de '+g.name);tableOptions(table,g.tableId);table.onchange=()=>{g.tableId=table.value?Number(table.value):null;save();renderTables()};const status=document.createElement('select');status.setAttribute('aria-label','Confirmación de '+g.name);status.replaceChildren(new Option('Pendiente','pending'),new Option('Confirmado','confirmed'),new Option('No asistirá','declined'));status.value=g.status;status.onchange=()=>{g.status=status.value;save();renderTables()};row.append(info,table,status,button('×',()=>{data.guests=data.guests.filter(v=>v.id!==g.id);save();renderGuests();renderTables()}));host.append(row)}if(guests.length>200){const p=document.createElement('p');p.textContent='Mostrando 200 resultados. Usa el buscador para encontrar a cualquier invitado.';host.append(p)}if(!guests.length){const p=document.createElement('p');p.className='note';p.textContent='Agrega invitados o busca otro nombre.';host.append(p)}}
function renderTables(){const host=$('tableRoster');host.replaceChildren();for(const t of engine.state.tables){const card=document.createElement('article');card.className='roster-card';const title=document.createElement('strong'),info=document.createElement('p'),names=document.createElement('p');const guests=active().filter(g=>g.tableId===t.id);title.textContent=tableName(t);info.textContent=guests.length+' / '+t.seats+' lugares · '+({round:'Redonda',rectangle:'Rectangular',square:'Cuadrada'}[t.shape]);names.textContent=guests.map(g=>g.name).join(', ')||'Sin invitados asignados';names.className='note';if(guests.length>t.seats)card.classList.add('warning');card.append(title,info,names,button('Editar mesa',()=>{engine.selectTable(t.id);$('managerDialog').close();$('tablesBlock').scrollIntoView({block:'start',behavior:'smooth'})}));host.append(card)}}
function renderTasks(){const host=$('taskRows');host.replaceChildren();for(const t of data.tasks.slice().sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'))){const row=document.createElement('div');row.className='task-row';const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=t.done;check.onchange=()=>{t.done=check.checked;save()};label.append(check,document.createTextNode((t.time?t.time+' · ':'')+t.title));row.append(label,button('Eliminar',()=>{data.tasks=data.tasks.filter(v=>v.id!==t.id);save();renderTasks()}));host.append(row)}}
function renderExpenses(){const host=$('expenseRows');host.replaceChildren();for(const e of data.expenses){const row=document.createElement('div');row.className='task-row';const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=e.paid;check.onchange=()=>{e.paid=check.checked;save()};label.append(check,document.createTextNode(e.title+' · '+new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(e.amount)));row.append(label,button('Eliminar',()=>{data.expenses=data.expenses.filter(v=>v.id!==e.id);save();renderExpenses()}));host.append(row)}}
function renderAll(){renderSummary();renderGuests();renderTables();renderTasks();renderExpenses();$('eventNotes').value=data.notes;$('expectedGuests').value=data.expected;tableOptions($('guestTableInput'),null)}
$('managerOpen').onclick=()=>{renderAll();$('managerDialog').showModal()};$('guestSearch').oninput=renderGuests;
$('guestForm').onsubmit=e=>{e.preventDefault();const names=$('guestNames').value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(data.guests.length+names.length>2000){studio.message('El evento admite hasta 2000 invitados');return}for(const name of names)data.guests.push({id:crypto.randomUUID(),name:name.slice(0,100),group:$('guestGroup').value.slice(0,80),notes:$('guestNotesInput').value.slice(0,300),tableId:$('guestTableInput').value?Number($('guestTableInput').value):null,status:'pending'});$('guestNames').value='';save();renderGuests();renderTables()};
$('assignGuests').onclick=()=>{let assigned=0;const guests=active(),ids=new Set(engine.state.tables.map(t=>t.id));for(const g of guests.filter(g=>!ids.has(g.tableId))){const table=engine.state.tables.find(t=>guests.filter(v=>v.tableId===t.id).length<t.seats);if(!table)break;g.tableId=table.id;assigned++}save();renderGuests();renderTables();studio.message(assigned+' invitados asignados a lugares libres')};
$('taskForm').onsubmit=e=>{e.preventDefault();if(data.tasks.length>=200)return studio.message('El límite es de 200 actividades');data.tasks.push({id:crypto.randomUUID(),title:$('taskTitle').value.trim().slice(0,150),time:$('taskTime').value,done:false});$('taskTitle').value='';save();renderTasks()};
$('expenseForm').onsubmit=e=>{e.preventDefault();if(data.expenses.length>=200)return studio.message('El límite es de 200 conceptos');const amount=Number($('expenseAmount').value);if(!Number.isFinite(amount)||amount<0||amount>100000000)return;data.expenses.push({id:crypto.randomUUID(),title:$('expenseTitle').value.trim().slice(0,100),amount,paid:false});$('expenseTitle').value='';$('expenseAmount').value='';save();renderExpenses()};$('eventNotes').oninput=()=>{data.notes=$('eventNotes').value.slice(0,10000);save()};$('expectedGuests').onchange=()=>{data.expected=Math.max(0,Math.min(2000,Math.round(Number($('expectedGuests').value)||0)));save()};
function csv(rows){const quote=v=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};return '\ufeff'+rows.map(r=>r.map(quote).join(',')).join('\r\n')}
$('guestCSV').onclick=()=>JCHShare.save(csv([['Invitado','Grupo','Mesa','Confirmación','Notas'],...data.guests.map(g=>[g.name,g.group,engine.state.tables.find(t=>t.id===g.tableId)?tableName(engine.state.tables.find(t=>t.id===g.tableId)):'Sin mesa',g.status,g.notes])]),JCHShare.filename(studio.meta().title)+'-invitados.csv','text/csv;charset=utf-8');
function backup(){return {...structuredClone(engine.state),_jch:{version:1,meta:studio.meta(),administration:structuredClone(data)}}}
$('eventBackup').onclick=()=>JCHShare.save(JSON.stringify(backup(),null,2),JCHShare.filename(studio.meta().title)+'-evento.json','application/json');$('eventImport').onclick=()=>$('eventBackupFile').click();$('eventBackupFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>3000000)throw Error('El respaldo supera 3 MB');const raw=JSON.parse(await file.text()),layout=engine.validate(raw),admin=clean(raw._jch?.administration);if(engine.state.tables.length&&!confirm('¿Abrir este evento y sustituir la distribución actual?'))return;engine.restore(layout);studio.setMeta(raw._jch?.meta||{title:file.name.replace(/\.json$/i,'')});restore(admin);studio.message('Evento y organización recuperados')}catch(e){studio.message(e.message)}finally{e.target.value=''}};
$('printSeating').onclick=()=>{const w=window.open('about:blank','_blank');if(!w)return studio.message('Permite ventanas emergentes para imprimir');w.opener=null;const doc=w.document;doc.title=studio.meta().title;const style=doc.createElement('style');style.textContent='body{font:14px system-ui;margin:35px;color:#243a2d}h1{font-size:24px}article{break-inside:avoid;border:1px solid #ccc;padding:16px;margin:12px 0}button{padding:10px}@media print{button{display:none}}';doc.head.append(style);const heading=doc.createElement('h1');heading.textContent=studio.meta().title;doc.body.append(heading);const date=doc.createElement('p');date.textContent=studio.meta().date;doc.body.append(date);for(const t of engine.state.tables){const a=doc.createElement('article'),h=doc.createElement('h2'),p=doc.createElement('p');h.textContent=tableName(t)+' · '+t.seats+' lugares';p.textContent=active().filter(g=>g.tableId===t.id).map(g=>g.name).join(', ')||'Sin asignación';a.append(h,p);doc.body.append(a)}const unassigned=doc.createElement('p');unassigned.textContent='Sin mesa: '+active().filter(g=>!engine.state.tables.some(t=>t.id===g.tableId)).map(g=>g.name).join(', ');doc.body.append(unassigned);const b=doc.createElement('button');b.textContent='Imprimir / guardar PDF';b.onclick=()=>w.print();doc.body.prepend(b)};
document.querySelectorAll('[data-manager-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-manager-tab]').forEach(v=>v.setAttribute('aria-selected',String(v===b)));document.querySelectorAll('[data-manager-panel]').forEach(p=>p.hidden=p.dataset.managerPanel!==b.dataset.managerTab)});
document.addEventListener('jch:change',()=>{renderSummary();if($('managerDialog').open){renderTables();renderGuests();tableOptions($('guestTableInput'),Number($('guestTableInput').value)||null)}});
window.JCHEvents={data:()=>structuredClone(data),restore,summary,backup};renderAll();
})();
