(()=>{'use strict';
const THREE=window.THREE;
const muralTexture=new THREE.Texture();muralTexture.colorSpace=THREE.SRGBColorSpace;
const assetsReady=new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{muralTexture.image=img;muralTexture.needsUpdate=true;resolve()};img.onerror=()=>reject(new Error('No se pudo cargar la textura del salón'));img.src='/assets/textures/encanto-mural.jpg'});
assetsReady.catch(()=>{});
const tableDefaults={shape:'round',w:1.8,d:1.8,seats:10,angle:0,chairGap:.08,chairWidth:.42,chairDepth:.42,tableHeight:.77,tableColor:'#f4eee1',chairColor:'#eee9dc',cushionColor:'#fffdf4',label:'',chairMode:'auto',chairSides:[0,0,0,0],customChairs:[],chairArcStart:0,chairArcSpan:360};
function createTiffanyGeometry(){
 const pieces=[];
 function rod(a,b,r=.014){a=new THREE.Vector3(...a);b=new THREE.Vector3(...b);const g=new THREE.CylinderGeometry(r,r,a.distanceTo(b),6);const m=new THREE.Matrix4().compose(a.clone().add(b).multiplyScalar(.5),new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize()),new THREE.Vector3(1,1,1));pieces.push(g.toNonIndexed().applyMatrix4(m));g.dispose()}
 for(const x of [-.19,.19]){rod([x,0,-.19],[x,.45,-.19],.017);rod([x,0,.19],[x,.99,.19],.017);rod([x,.2,-.19],[x,.2,.19]);}
 for(const z of [-.19,.19])rod([-.19,.2,z],[.19,.2,z]);
 for(const y of [.48,.68,.82,.96])rod([-.19,y,.19],[.19,y,.19],y===.96?.02:.014);
 for(const x of [-.095,0,.095])rod([x,.48,.19],[x,.96,.19],.01);
 for(const x of [-.19,.19])for(const y of [.57,.75,.91]){const g=new THREE.SphereGeometry(.023,6,4).toNonIndexed();g.translate(x,y,.19);pieces.push(g)}
 const g=new THREE.BufferGeometry();for(const key of ['position','normal','uv']){const length=pieces.reduce((n,p)=>n+p.attributes[key].array.length,0),a=new Float32Array(length);let offset=0;for(const p of pieces){a.set(p.attributes[key].array,offset);offset+=p.attributes[key].array.length}g.setAttribute(key,new THREE.BufferAttribute(a,key==='uv'?2:3))}pieces.forEach(p=>p.dispose());return g;
}
function normalizeTable(t){
 if(!t||!Number.isSafeInteger(t.id)||t.id<1||!['round','rectangle','square'].includes(t.shape))throw Error('Mesa no válida');
 const result={...tableDefaults,...t};
 for(const [key,min,max]of [['x',0,40],['z',0,60],['w',.6,4],['d',.6,4],['seats',0,16],['chairGap',0,1.2],['chairWidth',.3,.65],['chairDepth',.3,.65],['tableHeight',.6,1.2],['angle',-3600,3600]])if(!Number.isFinite(result[key])||result[key]<min||result[key]>max)throw Error('Medida no válida: '+key);
 if(!Number.isInteger(result.seats))throw Error('El número de sillas debe ser entero');
 for(const key of ['chairColor','tableColor','cushionColor'])if(typeof result[key]!=='string'||!/^#[\da-f]{6}$/i.test(result[key]))throw Error('Color no válido');
 if(typeof result.label!=='string'||result.label.length>40)throw Error('El nombre admite hasta 40 caracteres');
 if(!['auto','front','right','back','left','opposite','sides','manual'].includes(result.chairMode))throw Error('Distribución de sillas no válida');
 if(!Array.isArray(result.chairSides)||result.chairSides.length!==4||result.chairSides.some(n=>!Number.isInteger(n)||n<0||n>16)||result.chairSides.reduce((a,b)=>a+b,0)>16)throw Error('Reparte como máximo 16 sillas entre los cuatro lados');
 if(!Array.isArray(result.customChairs)||result.customChairs.length>16)throw Error('Posiciones de sillas no válidas');
 result.customChairs=result.customChairs.map(p=>{if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.z)||Math.abs(p.x)>6||Math.abs(p.z)>6||!Number.isFinite(p.angle)||Math.abs(p.angle)>3600)throw Error('Posición de silla no válida');return {x:p.x,z:p.z,angle:normalizeAngle(p.angle)}});
 for(const [k,min,max] of [['chairArcStart',0,360],['chairArcSpan',30,360]])if(!Number.isFinite(result[k])||result[k]<min||result[k]>max)throw Error('Arco de sillas no válido');
 if(result.chairMode==='sides'&&result.shape!=='round')result.seats=result.chairSides.reduce((a,b)=>a+b,0);
 result.angle=normalizeAngle(result.angle);if(t.chairGap===undefined)result.chairGap=.22;if(result.shape!=='rectangle')result.d=result.w;
 return Object.fromEntries(['id','shape','x','z','w','d','seats','angle','chairGap','chairWidth','chairDepth','tableHeight','tableColor','chairColor','cushionColor','label','chairMode','chairSides','customChairs','chairArcStart','chairArcSpan'].map(k=>[k,result[k]]));
}
function chairLayout(t){
 const n=t.seats,offset=t.chairDepth/2+t.chairGap,positions=[],mode=t.chairMode||'auto';
 if(mode==='manual'){const fallback=chairLayout({...t,chairMode:'auto'});return Array.from({length:n},(_,i)=>{const p=t.customChairs?.[i];return p?{x:p.x,z:p.z,angle:THREE.MathUtils.degToRad(p.angle)}:fallback[i]})}
 if(t.shape==='round'){const side={front:0,right:90,back:180,left:270},span=side[mode]!==undefined?90:(t.chairArcSpan??360),start=side[mode]!==undefined?side[mode]-span/2:(t.chairArcStart??0);for(let i=0;i<n;i++){const a=THREE.MathUtils.degToRad(start+(span===360?i/n: n===1?.5:i/(n-1))*span);positions.push({x:Math.sin(a)*(t.w/2+offset),z:Math.cos(a)*(t.w/2+offset),angle:a})}return positions}
 const lengths=[t.w,t.d,t.w,t.d],total=2*(t.w+t.d),expected=lengths.map(l=>n*l/total);let counts;
 const side=['front','right','back','left'].indexOf(mode);
 if(side>=0){counts=[0,0,0,0];counts[side]=n}
 else if(mode==='sides')counts=[...t.chairSides];
 else if(mode==='opposite'){counts=t.w>=t.d?[Math.ceil(n/2),0,Math.floor(n/2),0]:[0,Math.ceil(n/2),0,Math.floor(n/2)]}
 else{counts=expected.map(v=>Math.max(n>=4?1:0,Math.floor(v)));while(counts.reduce((a,b)=>a+b,0)<n){let best=0;counts.forEach((v,i)=>{if(expected[i]-v>expected[best]-counts[best])best=i});counts[best]++}while(counts.reduce((a,b)=>a+b,0)>n){let best=-1;counts.forEach((v,i)=>{if(v>(n>=4?1:0)&&(best<0||v-expected[i]>counts[best]-expected[best]))best=i});counts[best]--}}
 for(let side=0;side<4;side++)for(let i=0;i<counts[side];i++){const along=((i+.5)/counts[side]-.5)*lengths[side],a=side*Math.PI/2;positions.push({x:side===1?t.w/2+offset:side===3?-t.w/2-offset:side===0?along:-along,z:side===0?t.d/2+offset:side===2?-t.d/2-offset:side===1?-along:along,angle:a})}
 return positions;
}
function tableNumber(layout,t){return layout.tables.findIndex(v=>v.id===(typeof t==='object'?t.id:t))+1}
function addTableBadge(group,t,number){const c=document.createElement('canvas');c.width=256;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#fffdf4';ctx.fillRect(0,0,256,128);ctx.strokeStyle='#b79b54';ctx.lineWidth=7;ctx.strokeRect(5,5,246,118);ctx.fillStyle='#304b37';ctx.font='bold 76px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('M'+number,128,70);const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;const mat=new THREE.MeshStandardMaterial({map,roughness:.85,side:THREE.DoubleSide});const badge=new THREE.Mesh(new THREE.PlaneGeometry(.5,.25),mat);badge.rotation.x=-Math.PI/2;badge.position.y=t.tableHeight+.039;badge.name='Número de mesa M'+number;group.add(badge);group.userData.materials.push(mat)}
function validate(s){
 if(!s||s.version!==1||!['inside','outside'].includes(s.extent)||!Array.isArray(s.tables)||s.tables.length>100)throw Error('Archivo de distribución no válido');
 const venue=s.venue??'encanto';if(!JCHVenues.names[venue])throw Error('Salón no válido');
 for(const [k,min,max] of [['stageH',.1,1.5],['rampL',2,7],['floorX',0,40],['floorZ',0,60]])if(!Number.isFinite(s[k])||s[k]<min||s[k]>max)throw Error('Medida no válida: '+k);
 const extra={};if(venue==='espejos'){if(s.extent!=='inside')throw Error('Espejos tiene un recinto cerrado');for(const [k,min,max,fallback] of [['hallW',12,24,16],['hallD',18,40,28],['floorW',2,10,5.8],['floorD',2,16,12]]){const v=s[k]??fallback;if(!Number.isFinite(v)||v<min||v>max)throw Error('Medida no válida: '+k);extra[k]=v}}
 const m=JCHVenues.metrics({...s,venue,...extra}),tables=s.tables.map(normalizeTable),ids=new Set();for(const t of tables){if(ids.has(t.id))throw Error('ID de mesa duplicado');if(t.x>m.W||t.z>m.D)throw Error('La mesa queda fuera de las coordenadas del salón');ids.add(t.id)}
 const angle=s.floorAngle===undefined?0:s.floorAngle;if(!Number.isFinite(angle)||Math.abs(angle)>3600)throw Error('Ángulo de pista no válido');const b=floorBounds(angle,{...s,venue,...extra});
 if(s.floorX<m.minX+b.x-1e-6||s.floorX>m.W-b.x+1e-6||s.floorZ<b.z-1e-6||s.floorZ>m.D-b.z+1e-6)throw Error(venue==='espejos'?'La pista debe quedar dentro del salón':'La pista debe quedar dentro del área de pasto');
 return {version:1,venue,extent:s.extent,stageH:s.stageH,rampL:s.rampL,floorX:s.floorX,floorZ:s.floorZ,floorAngle:normalizeAngle(angle),...extra,tables};
}
function normalizeAngle(a){return Math.round(((a%360)+360)%360*100)/100}
function floorBounds(angle,layout=JCHVenues.defaults()){const a=THREE.MathUtils.degToRad(angle),m=JCHVenues.metrics(layout);return {x:Math.abs(Math.cos(a))*m.floorW/2+Math.abs(Math.sin(a))*m.floorD/2,z:Math.abs(Math.sin(a))*m.floorW/2+Math.abs(Math.cos(a))*m.floorD/2}}
function exportGLB(model,state,groups={}){
model.updateMatrixWorld(true);let chunks=[],offset=0;const data={asset:{version:'2.0',generator:JCHVenues.names[state.venue||'encanto']+', escala en metros'},scene:0,scenes:[{nodes:[]}],nodes:[],meshes:[],materials:[],textures:[],images:[],samplers:[{magFilter:9729,minFilter:9987,wrapS:10497,wrapT:10497}],buffers:[{byteLength:0}],bufferViews:[],accessors:[],extras:{unit:'meters',layout:{...state,tables:state.tables.map(t=>({...t}))},tableLayout:state.tables.map(t=>({...t})),danceFloorPlacement:{x:state.floorX,z:state.floorZ,angleDegrees:state.floorAngle},venue:state.venue||'encanto',confirmedDimensions:state.venue==='espejos'?{}:{venue:[state.extent==='inside'?20:23,20],danceFloor:[7.3,5],stage:[3,20]},estimatedDimensions:state.venue==='espejos'?{venue:[state.hallW,state.hallD],danceFloor:[state.floorW,state.floorD]}:{},approximate:state.venue==='espejos'?['all architectural dimensions','levels','object positions','mirror reflections']:['stage height','ramp dimensions','roof','entry dimensions','object positions']}};const mm=new Map(),tm=new Map();
function bytesView(bytes,target){const copy=new Uint8Array((bytes.length+3)&~3);copy.set(bytes);const entry={buffer:0,byteOffset:offset,byteLength:bytes.length};if(target)entry.target=target;const id=data.bufferViews.push(entry)-1;chunks.push(copy);offset+=copy.length;return id}
function arr(a,type,count,min,max){let bv=bytesView(new Uint8Array(a.buffer,a.byteOffset,a.byteLength),34962),ac={bufferView:bv,componentType:5126,count,type};if(min)ac.min=min;if(max)ac.max=max;return data.accessors.push(ac)-1}
function tex(map){if(tm.has(map))return tm.get(map);const img=map.image;if(!img)return null;const c=document.createElement('canvas');c.width=img.width;c.height=img.height;c.getContext('2d').drawImage(img,0,0);const encoded=c.toDataURL('image/png').split(',')[1],str=atob(encoded),bytes=new Uint8Array(str.length);for(let i=0;i<str.length;i++)bytes[i]=str.charCodeAt(i);let view=bytesView(bytes),imageIndex=data.images.push({bufferView:view,mimeType:'image/png'})-1;let index=data.textures.push({sampler:0,source:imageIndex})-1;tm.set(map,index);return index}
model.traverse(o=>{if(!o.isMesh||!o.geometry)return;let source=o.geometry.index?o.geometry.toNonIndexed():o.geometry,g=source.clone().applyMatrix4(o.matrixWorld);if(o.matrixWorld.determinant()<0){for(const attr of Object.values(g.attributes)){for(let i=0;i<attr.count;i+=3){for(let j=0;j<attr.itemSize;j++){let a=(i+1)*attr.itemSize+j,b=(i+2)*attr.itemSize+j,v=attr.array[a];attr.array[a]=attr.array[b];attr.array[b]=v}}}}let p=g.attributes.position,n=g.attributes.normal;if(!p||!n)return;let mi=Array.isArray(o.material)?o.material[0]:o.material;
if(!mm.has(mi)){let c=mi.color||new THREE.Color(0xffffff);let parent=o;while(parent&&parent.userData.tableId===undefined)parent=parent.parent;const table=parent&&state.tables.find(t=>t.id===parent.userData.tableId);if(table&&mi===parent.userData.topMaterial)c=new THREE.Color(table.tableColor);let m={name:o.name||'Material',pbrMetallicRoughness:{baseColorFactor:[c.r,c.g,c.b,mi.opacity??1],metallicFactor:mi.metalness??0,roughnessFactor:mi.roughness??.85},doubleSided:true};if(mi.transparent)m.alphaMode='BLEND';if(mi.emissive)m.emissiveFactor=mi.emissive.clone().multiplyScalar(mi.emissiveIntensity??1).toArray();if(mi.name)m.name=mi.name;if(mi.map){let index=tex(mi.map);if(index!==null)m.pbrMetallicRoughness.baseColorTexture={index}}mm.set(mi,data.materials.length);data.materials.push(m)}
let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<p.count;i++)for(let j=0;j<3;j++){let v=p.array[i*3+j];min[j]=Math.min(min[j],v);max[j]=Math.max(max[j],v)}let attributes={POSITION:arr(new Float32Array(p.array),'VEC3',p.count,min,max),NORMAL:arr(new Float32Array(n.array),'VEC3',n.count)};if(mi.map&&g.attributes.uv){let uv=g.attributes.uv,vals=new Float32Array(uv.array);for(let i=0;i<uv.count;i++){vals[i*2]*=mi.map.repeat.x;vals[i*2+1]=1-vals[i*2+1]*mi.map.repeat.y}attributes.TEXCOORD_0=arr(vals,'VEC2',uv.count)}let mesh=data.meshes.push({name:o.name||'Elemento',primitives:[{attributes,material:mm.get(mi)}]})-1,node=data.nodes.push({name:o.name||'Elemento',mesh,extras:{category:/Cubierta|Techo/i.test(o.name)?'roof':/Muro de fondo|Mural de fondo/.test(o.name)?'wall':'main'}})-1;data.scenes[0].nodes.push(node);g.dispose();if(source!==o.geometry)source.dispose()});
data.buffers[0].byteLength=offset;let json=new TextEncoder().encode(JSON.stringify(data)),jlen=(json.length+3)&~3,total=12+8+jlen+8+offset,buf=new ArrayBuffer(total),v=new DataView(buf);v.setUint32(0,0x46546c67,true);v.setUint32(4,2,true);v.setUint32(8,total,true);v.setUint32(12,jlen,true);v.setUint32(16,0x4e4f534a,true);let jb=new Uint8Array(buf,20,jlen);jb.fill(32);jb.set(json);let bo=20+jlen;v.setUint32(bo,offset,true);v.setUint32(bo+4,0x004e4942,true);let pos=bo+8;for(const c of chunks){new Uint8Array(buf,pos,c.length).set(c);pos+=c.length}return buf}
function hasParent(o,p){while(o){if(o===p)return true;o=o.parent}return false}

function createVenue(layout,options={}){
 const state=validate(layout),scene=options.scene||new THREE.Scene();
 let model,roofGroup,dimGroup,tableGroup,floorGroup,floorDims,floorSelection,selected=null;
 const materials={},sharedBox=new THREE.BoxGeometry(1,1,1),sharedRound=new THREE.CylinderGeometry(.5,.5,.07,48),chairGeometry=createTiffanyGeometry();
 const flushTables=()=>{},updateStatus=()=>{};
function makeTable(t){
 const group=new THREE.Group();group.position.set(t.x,JCHVenues.surface(state,t.x,t.z),t.z);group.rotation.y=THREE.MathUtils.degToRad(t.angle);group.userData.tableId=t.id;group.name='Mesa '+tableNumber(state,t);
 const topMat=mat(selected===t.id?0xd5b85c:t.tableColor),chairMat=mat(t.chairColor,{roughness:.45}),cushionMat=mat(t.cushionColor);group.userData.topMaterial=topMat;group.userData.materials=[topMat,chairMat,cushionMat];
 if(t.shape==='round'){const top=new THREE.Mesh(sharedRound,topMat);top.position.y=t.tableHeight;top.scale.set(t.w,1,t.w);top.name='Mesa redonda';top.castShadow=true;top.receiveShadow=true;group.add(top);box(.12,t.tableHeight-.035,.12,0,(t.tableHeight-.035)/2,0,materials.steel,group)}else{box(t.w,.07,t.d,0,t.tableHeight,0,topMat,group,'Mesa '+t.shape);for(const x of [-t.w*.4,t.w*.4])for(const z of [-t.d*.36,t.d*.36])box(.07,t.tableHeight-.035,.07,x,(t.tableHeight-.035)/2,z,materials.steel,group)}
 chairLayout(t).forEach((p,i)=>{const chair=new THREE.Group();chair.name='Silla Tiffany '+(i+1);chair.userData.chairIndex=i;chair.position.set(p.x,0,p.z);chair.rotation.y=p.angle;chair.scale.set(t.chairWidth/.42,1,t.chairDepth/.42);const frame=new THREE.Mesh(chairGeometry,chairMat);frame.name='Estructura Tiffany';frame.castShadow=true;chair.add(frame);box(.4,.06,.4,0,.45,0,cushionMat,chair,'Cojín Tiffany');group.add(chair)});
 addTableBadge(group,t,tableNumber(state,t));label('M'+tableNumber(state,t)+(t.label?' · '+t.label:''),0,Math.max(1.23,t.tableHeight+.4),0,.3,'#304b37',group);tableGroup.add(group);return group;
}
function mat(color,other={}){return new THREE.MeshStandardMaterial({color,roughness:.85,...other})}
const C={grass:0x648044,stone:0xe5e3d7,stage:0xa87757,cream:0xf2f0e7,white:0xeceee7,red:0xb52b39,teal:0x1693a3,yellow:0xefd535,dark:0x252a2b,steel:0xe8e9df};
function texture(kind){const c=document.createElement('canvas');c.width=c.height=512;let g=c.getContext('2d');let seed=38;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647};if(kind==='grass'){g.fillStyle='#5b793f';g.fillRect(0,0,512,512);for(let i=0;i<26000;i++){let v=rand();g.strokeStyle=v>.5?'rgba(170,180,100,.2)':'rgba(36,57,27,.23)';g.beginPath();let x=rand()*512,y=rand()*512;g.moveTo(x,y);g.lineTo(x+rand()*3-1.5,y-2-rand()*5);g.stroke()}}else{g.fillStyle='#dddccf';g.fillRect(0,0,512,512);for(let row=0;row<9;row++){for(let col=-1;col<8;col++){let x=col*75+(row%2?30:0),y=row*60;g.fillStyle=['#484b46','#636760','#757871','#525751'][Math.floor(rand()*4)];g.beginPath();g.moveTo(x+5,y+5);g.lineTo(x+67,y+2+rand()*8);g.lineTo(x+72,y+47);g.lineTo(x+40,y+57);g.lineTo(x+3,y+49);g.closePath();g.fill()}}}let t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;t.repeat.set(kind==='grass'?8:7,kind==='grass'?8:2);return t}
function box(w,h,d,x,y,z,m,parent=model,name=''){let o=new THREE.Mesh(sharedBox,m);o.position.set(x,y,z);o.scale.set(w,h,d);o.castShadow=true;o.receiveShadow=true;o.name=name;parent.add(o);return o}
function beam(a,b,r,m,parent=model){a=new THREE.Vector3(...a);b=new THREE.Vector3(...b);let o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,a.distanceTo(b),8),m);o.position.copy(a).add(b).multiplyScalar(.5);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.sub(a).normalize());o.castShadow=true;parent.add(o);return o}
function label(text,x,y,z,size=1,color='#3b5041',parent=dimGroup){const c=document.createElement('canvas');c.width=1024;c.height=160;const g=c.getContext('2d');g.fillStyle='rgba(250,250,242,.94)';g.fillRect(0,0,1024,160);g.fillStyle=color;g.font='500 66px Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(text,512,84);let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const o=new THREE.Sprite(new THREE.SpriteMaterial({map:t,depthTest:false}));o.position.set(x,y,z);o.scale.set(size*5.4,size*.84,1);o.renderOrder=100;parent.add(o);return o}
function line(a,b,color=0x3d5140,parent=dimGroup){let g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...a),new THREE.Vector3(...b)]);parent.add(new THREE.Line(g,new THREE.LineBasicMaterial({color})))}
function dim(a,b,text,pos,parent=dimGroup){line(a,b,0x3d5140,parent);const along=new THREE.Vector3(...b).sub(new THREE.Vector3(...a)).normalize();let cross=new THREE.Vector3(-along.z,0,along.x).multiplyScalar(.17);for(const p of [a,b])line([p[0]+cross.x,p[1],p[2]+cross.z],[p[0]-cross.x,p[1],p[2]-cross.z],0x3d5140,parent);label(text,...pos,1,'#3b5041',parent)}
function archBoard(x,z){const sh=new THREE.Shape();sh.moveTo(-1.95,0);sh.lineTo(-1.95,3.8);sh.lineTo(1.95,3.8);sh.lineTo(1.95,0);sh.lineTo(1.35,0);sh.lineTo(1.35,1.0);sh.quadraticCurveTo(1.35,2.05,.55,2.05);sh.lineTo(-.55,2.05);sh.quadraticCurveTo(-1.35,2.05,-1.35,1);sh.lineTo(-1.35,0);sh.closePath();let o=new THREE.Mesh(new THREE.ExtrudeGeometry(sh,{depth:.12,bevelEnabled:false}),materials.teal);o.position.set(x,1.2,z);o.name='Arco decorativo de trajinera';model.add(o);beam([x-1.95,1.2,z-.02],[x-1.95,5,z-.02],.06,materials.yellow);beam([x+1.95,1.2,z-.02],[x+1.95,5,z-.02],.06,materials.yellow);beam([x-1.95,5,z-.02],[x+1.95,5,z-.02],.06,materials.yellow);
const c=document.createElement('canvas');c.width=1024;c.height=180;let ctx=c.getContext('2d');ctx.fillStyle='#166c80';ctx.fillRect(0,0,1024,180);ctx.strokeStyle='#e5c834';ctx.lineWidth=18;ctx.strokeRect(7,7,1010,166);ctx.fillStyle='#f6f0dd';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 69px Georgia';ctx.fillText('XOCHIMILCO MÁGICO',512,95);let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;let s=new THREE.Mesh(new THREE.PlaneGeometry(3.6,.65),new THREE.MeshStandardMaterial({map:t,side:THREE.DoubleSide}));s.position.set(x,4.62,z-.04);s.rotation.y=0;model.add(s);
const c2=document.createElement('canvas');c2.width=1024;c2.height=250;let q=c2.getContext('2d');q.fillStyle='#578258';q.fillRect(0,0,1024,250);q.fillStyle='#faf2d4';q.font='bold 160px Georgia';q.textAlign='center';q.textBaseline='middle';q.fillText('AMELIA',512,137);let t2=new THREE.CanvasTexture(c2);t2.colorSpace=THREE.SRGBColorSpace;s=new THREE.Mesh(new THREE.PlaneGeometry(2.65,.72),new THREE.MeshStandardMaterial({map:t2,side:THREE.DoubleSide}));s.position.set(x,3.75,z-.045);s.rotation.y=0;model.add(s);}
function foliage(x,z,h=2.2){let g=new THREE.Group();g.position.set(x,0,z);model.add(g);box(.25,h,.25,0,h/2,0,materials.wood,g);let o=new THREE.Mesh(new THREE.IcosahedronGeometry(.9,1),materials.leaf);o.scale.set(1,h*.58,1);o.position.y=h*.77;g.add(o)}
function ramp(){let z1=18-state.rampL,z2=18,x1=3,x2=4.4,h=state.stageH;let pts=[x1,0,z1,x2,0,z1,x1,h,z2,x2,h,z2,x1,0,z2,x2,0,z2];let ix=[0,2,1,1,2,3,0,4,2,1,3,5,2,4,3,3,4,5,0,1,4,1,5,4];let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));g.setIndex(ix);g.setAttribute('uv',new THREE.Float32BufferAttribute([0,0,1,0,0,1,1,1,0,1,1,1],2));g.computeVertexNormals();let o=new THREE.Mesh(g,materials.grass);o.castShadow=true;o.receiveShadow=true;o.name='Rampa lateral izquierda aproximada';model.add(o);box(1.4,h,1.2,3.7,h/2,18.6,materials.stage);for(const x of [3.05,4.35]){beam([x,.85,z1],[x,h+.85,z2],.035,materials.steel);for(let i=0;i<4;i++){let t=i/3,z=z1+(z2-z1)*t,base=h*t;beam([x,base,z],[x,base+.85,z],.025,materials.steel)}}}
function build(){flushTables();model=new THREE.Group();model.scale.z=-1;scene.add(model);roofGroup=new THREE.Group();dimGroup=new THREE.Group();tableGroup=new THREE.Group();model.add(roofGroup,dimGroup,tableGroup);if(state.venue==='espejos'){({floorGroup,floorDims,floorSelection}=JCHVenues.buildEspejos({s:state,model,roofGroup,dimGroup,tableGroup,mat,box,beam,label,dim,makeTable}));roofGroup.visible=!!options.roof;dimGroup.visible=!!options.dimensions;return}const W=state.extent==='inside'?20:23,cx=(W+3)/2;
box(W,.3,20,W/2,-.18,10,materials.base,model,'Base '+W+' × 20 m');box(W-3,.045,20,(W+3)/2,.012,10,materials.grass,model,'Pasto');box(3,state.stageH,20,1.5,state.stageH/2,10,materials.stage,model,'Escenario 3 × 20 m');box(.1,state.stageH+.12,20,3,state.stageH/2,10,materials.stone);box(.2,.8,20,W-.1,.4,10,materials.stone);box(.2,.8,20,.1,.4,10,materials.stone);box(W,3.35,.22,W/2,1.67,20.08,materials.cream,model,'Muro de fondo');
const mural=new THREE.Mesh(new THREE.PlaneGeometry(W-3.4,2.8),materials.mural);mural.position.set((W+3)/2,1.58,19.945);mural.rotation.y=0;mural.name='Mural de fondo';model.add(mural);
for(let x=4;x<W-.7;x+=1.25){box(.6,.34,.5,x,.18,19.55,materials.wood);let p=new THREE.Mesh(new THREE.ConeGeometry(.31,.78,6),materials.leaf);p.position.set(x,.72,19.55);model.add(p)}
floorGroup=new THREE.Group();floorGroup.name='Pista móvil';floorGroup.userData.isFloor=true;model.add(floorGroup);floorDims=new THREE.Group();dimGroup.add(floorDims);
box(7.3,.12,5,0,.1,0,materials.floor,floorGroup,'Pista 7.30 × 5.00 m');for(let i=1;i<5;i++)line([-3.65+i*7.3/5,.164,-2.5],[-3.65+i*7.3/5,.164,2.5],0xc3c6bc,floorGroup);for(let i=1;i<4;i++)line([-3.65,.164,-2.5+i*1.25],[3.65,.164,-2.5+i*1.25],0xc3c6bc,floorGroup);
for(let i=0;i<12;i++)box(.61,.045,.035,-3.65+i*.61+.305,.093,-2.52,[materials.red,materials.teal,materials.floor][i%3],floorGroup);
floorSelection=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(7.36,.15,5.06)),new THREE.LineBasicMaterial({color:0xb89737,depthTest:false}));floorSelection.position.y=.11;floorSelection.renderOrder=90;floorGroup.add(floorSelection);
dim([-3.65,.23,-3],[3.65,.23,-3],'7.30 m',[0,.85,-3.15],floorDims);dim([4.1,.23,-2.5],[4.1,.23,2.5],'5.00 m',[4.5,.9,0],floorDims);label('PISTA',0,.6,0,.7,'#3b5041',floorDims);updateFloorTransform();ramp();
// Speakers at the rear end of the left stage, as in the reference.
box(.65,1.2,.6,1.1,state.stageH+.6,16.4,materials.dark,model,'Bocina');box(.65,1.2,.6,2.1,state.stageH+.6,18.7,materials.dark);beam([.65,state.stageH,17.6],[.65,3.4,17.6],.055,materials.steel);beam([2.4,state.stageH,17.6],[2.4,3.4,17.6],.055,materials.steel);beam([.65,3.4,17.6],[2.4,3.4,17.6],.055,materials.steel);
// Open tent structure. Roof is hidden by default for event layout.
const eave=3.8,ridge=6.3;for(const z of [.1,5,10,15,19.9]){for(const x of [.18,W-.18]){box(.22,eave,.22,x,eave/2,z,materials.steel,roofGroup);beam([x,eave,z],[W/2,ridge,z],.065,materials.steel,roofGroup)}beam([0,eave,z],[W,eave,z],.045,materials.steel,roofGroup);beam([W*.3,eave,z],[W/2,ridge,z],.033,materials.steel,roofGroup);beam([W*.7,eave,z],[W/2,ridge,z],.033,materials.steel,roofGroup)}beam([W/2,ridge,0],[W/2,ridge,20],.065,materials.steel,roofGroup);
for(let side=0;side<2;side++){let a=side?W:0;let geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute([a,eave,0,W/2,ridge,0,a,eave,20,W/2,ridge,20],3));geo.setIndex([0,1,2,1,3,2]);geo.computeVertexNormals();let o=new THREE.Mesh(geo,materials.roof);o.name='Cubierta a dos aguas aproximada';roofGroup.add(o)}
for(const x of [W*.27,W*.73])for(const z of [5,14]){beam([x,4.5,z],[x,3.05,z],.018,materials.dark,roofGroup);let wheel=new THREE.Mesh(new THREE.TorusGeometry(.65,.045,6,24),materials.dark);wheel.rotation.x=Math.PI/2;wheel.position.set(x,3.05,z);roofGroup.add(wheel);for(let a=0;a<Math.PI*2;a+=Math.PI/6)beam([x,3.05,z],[x+Math.cos(a)*.65,3.05,z+Math.sin(a)*.65],.012,materials.dark,roofGroup)}
// Trajinera-themed entry bridge outside the measured square. No car.
box(3,.07,5.8,cx,0,-2.9,materials.terracotta,model,'Pasillo de acceso aproximado');for(const x of [cx-1.65,cx+1.65]){box(.24,.4,4.8,x,.2,-2.6,materials.red);for(const z of [-.7,-4.6]){box(.12,3.6,.12,x,1.8,z,materials.yellow);box(.38,.25,.6,x,.52,z,materials.red);let plant=new THREE.Mesh(new THREE.IcosahedronGeometry(.27,1),materials.leaf);plant.position.set(x,.83,z);model.add(plant)}beam([x,3.6,-.7],[x,3.6,-4.6],.04,materials.teal)}archBoard(cx,-4.7);foliage(cx-4.1,-2.5,3.3);foliage(cx+4.1,-2.5,3.3);box(4,.035,5,cx-4.15,-.015,-2.5,materials.grass);box(4,.035,5,cx+4.15,-.015,-2.5,materials.grass);
dim([0,.07,-.6],[W,.07,-.6],W.toFixed(0)+' m',[W/2,.65,-.9]);dim([W+.7,.07,0],[W+.7,.07,20],'20 m',[W+1.1,.65,10]);label('ESCENARIO · 20 × 3 m',1.5,state.stageH+1.0,9,1.2);label('RAMPA',4.1,state.stageH+1.1,17.1,.65);label('ENTRADA',cx,.65,-6.2,.9);roofGroup.visible=!!options.roof;dimGroup.visible=!!options.dimensions;
state.tables.forEach(makeTable);updateStatus();}
function updateFloorTransform(){for(const group of [floorGroup,floorDims]){group.position.set(state.floorX,0,state.floorZ);group.rotation.y=THREE.MathUtils.degToRad(state.floorAngle);group.updateMatrixWorld(true)}floorSelection.visible=selected==='floor'}
for(const [k,v]of Object.entries(C))materials[k]=mat(v);materials.base=mat(0xc0c6b0);materials.wood=mat(0x9a7052);materials.leaf=mat(0x416035);materials.floor=mat(0xf4f3ea);materials.chair=mat(0xf6f1df);materials.terracotta=mat(0xb66d56);materials.grass=mat(0xffffff,{map:texture('grass')});materials.stone=mat(C.stone,{map:texture('stone')});materials.roof=mat(0xf1f0e8,{side:THREE.DoubleSide});materials.mural=mat(0x6f8a57,{side:THREE.DoubleSide});materials.mural.map=muralTexture;materials.mural.color.set(0xffffff);
 build();model.updateMatrixWorld(true);
 function dispose(){const geoms=new Set(),mats=new Set(),maps=new Set();model.traverse(o=>{if(o.geometry)geoms.add(o.geometry);if(o.material){for(const m of (Array.isArray(o.material)?o.material:[o.material])){mats.add(m);if(m.map&&m.map!==muralTexture&&!Object.values(JCHVenues.photos).includes(m.map))maps.add(m.map)}}});geoms.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());maps.forEach(t=>t.dispose());model.userData.reflectionTarget?.dispose();scene.remove(model)}
 return {model,roofGroup,dimGroup,tableGroup,floorGroup,floorDims,floorSelection,materials,dispose,glb:()=>exportGLB(model,state,{roofGroup}),layout:state};
}

function reflections(model,scene,renderer){
 const mirrored=[];model.traverse(o=>{if(o.isMesh&&(Array.isArray(o.material)?o.material:[o.material]).some(m=>/^Espejo ·/.test(m.name)))mirrored.push(o)});if(!mirrored.length)return;
 const rt=model.userData.reflectionTarget||(model.userData.reflectionTarget=new THREE.WebGLCubeRenderTarget(128,{generateMipmaps:true,minFilter:THREE.LinearMipmapLinearFilter})),cam=new THREE.CubeCamera(.1,100,rt),box=new THREE.Box3().setFromObject(model),center=box.getCenter(new THREE.Vector3());cam.position.set(center.x,box.min.y+1.7,center.z);
 const saved=[];model.traverse(o=>{if(mirrored.includes(o)||o.isSprite||o===model.children.find(v=>v.type==='Group'&&v.children.some(c=>c.isLine))){saved.push([o,o.visible]);o.visible=false}});scene.updateMatrixWorld(true);const oldTarget=renderer.getRenderTarget();try{cam.update(renderer,scene);mirrored.forEach(o=>{for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(/^Espejo ·/.test(m.name)){m.envMap=rt.texture;m.envMapIntensity=.85;m.needsUpdate=true}})}finally{saved.forEach(([o,v])=>o.visible=v);renderer.setRenderTarget(oldTarget)}
}
window.JCHModel={createVenue,exportGLB,validate,normalizeTable,chairLayout,tableNumber,addTableBadge,assetsReady,ready:venue=>venue==='espejos'?JCHVenues.ready(venue):assetsReady,defaultLayout:JCHVenues.defaults,floorBounds,reflections};
})();
