(()=>{'use strict';
const MAX_BYTES=180000,MAX_TOKEN=32000;
const SETTINGS={light:'studio',exposure:100,fill:100,background:'ivory',quality:'auto',roof:false,shadows:true};
function settings(value={}){return {light:['studio','day','warm'].includes(value.light)?value.light:'studio',exposure:clamp(value.exposure,35,200,100),fill:clamp(value.fill,20,200,100),background:['ivory','white','dark'].includes(value.background)?value.background:'ivory',quality:['auto','high','low'].includes(value.quality)?value.quality:'auto',roof:!!value.roof,shadows:value.shadows!==false}}
function clamp(v,min,max,fallback){return typeof v==='number'&&Number.isFinite(v)?Math.max(min,Math.min(max,v)):fallback}
function validatePresentation(value){if(!value||value.version!==1||value.venue!=='encanto')throw Error('Esta presentación no es compatible con JCH 3D');const p={version:1,venue:'encanto',title:typeof value.title==='string'?value.title.slice(0,100):'Salón Encanto',date:typeof value.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value.date)?value.date:'',settings:settings(value.settings)};if(value.layout){if(!window.JCHModel)throw Error('No se pudo iniciar el motor del salón');p.layout=JCHModel.validate(value.layout)}return p}
function b64(bytes){let out='';for(let i=0;i<bytes.length;i+=16384)out+=String.fromCharCode(...bytes.subarray(i,i+16384));return btoa(out)}
function unb64(str){if(!/^[A-Za-z0-9_-]+$/.test(str))throw Error('El enlace está incompleto o fue modificado');const raw=atob(str.replaceAll('-','+').replaceAll('_','/')),a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a}
async function encode(value){const p=validatePresentation(value);if(!p.layout)throw Error('La presentación necesita una distribución');let bytes=new TextEncoder().encode(JSON.stringify(p));if(bytes.length>MAX_BYTES)throw Error('La distribución supera el tamaño admitido');let prefix='u.';if(typeof CompressionStream!=='undefined'){bytes=new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('deflate'))).arrayBuffer());prefix='d.'}const token=prefix+b64(bytes).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');if(token.length>MAX_TOKEN)throw Error('Esta distribución es demasiado grande para un enlace. Descarga el visor HTML.');return token}
async function decode(token){if(typeof token!=='string'||token.length>MAX_TOKEN||!/^([du])\./.test(token))throw Error('El enlace de presentación no es válido');let bytes=unb64(token.slice(2));if(token[0]==='d'){if(typeof DecompressionStream==='undefined')throw Error('Actualiza tu navegador para abrir este enlace, o usa el visor HTML');const reader=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate')).getReader(),chunks=[];let length=0;try{while(true){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>MAX_BYTES){await reader.cancel();throw Error('La presentación supera el tamaño admitido')}chunks.push(value)}}finally{reader.releaseLock()}bytes=new Uint8Array(length);let pos=0;for(const part of chunks){bytes.set(part,pos);pos+=part.length}}if(bytes.length>MAX_BYTES)throw Error('La presentación supera el tamaño admitido');const p=validatePresentation(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes)));if(!p.layout)throw Error('Falta la distribución en el enlace');return p}
async function link(value){return new URL('/presentacion/',location.origin).href+'#jch='+await encode(value)}
let templatePromise;
async function template(){if(!templatePromise)templatePromise=fetch('/assets/viewer.template.html').then(r=>{if(!r.ok)throw Error('No se pudo preparar el visor offline');return r.text()}).catch(e=>{templatePromise=null;throw e});return templatePromise}
function safeJSON(value){return JSON.stringify(value).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029')}
async function html(bytes,value){const p=validatePresentation(value);delete p.layout;const base=await template();return base.replace('__JCH_MODEL_DATA__',b64(bytes)).replace('__JCH_PRESENTATION_DATA__',safeJSON(p))}
function save(data,name,type){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
function filename(title){return (title||'Salon_Encanto').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'_').slice(0,70)||'Salon_Encanto'}
async function downloadViewer(bytes,p){save(await html(bytes,p),filename(p.title)+'_Visor_3D_Offline.html','text/html;charset=utf-8')}
window.JCHShare={encode,decode,link,html,downloadViewer,validatePresentation,settings,defaults:SETTINGS,save,filename};
})();
