(()=>{'use strict';
const T=window.THREE;
const names={encanto:'Salón Encanto',espejos:'Salón de los Espejos'};
function metrics(s){const mirrors=s.venue==='espejos',W=mirrors?(s.hallW??16):(s.extent==='outside'?23:20),D=mirrors?(s.hallD??28):20;return {W,D,minX:mirrors?0:3,split:W*.4,entryX:mirrors?W*.7:(W+3)/2,floorW:mirrors?(s.floorW??5.8):7.3,floorD:mirrors?(s.floorD??12):5,estimated:mirrors}}
function surface(s,x,z){if(s.venue!=='espejos')return 0;const m=metrics(s);return x>=m.split?.4:z>m.D-4?s.stageH:0}
function obstacles(s){if(s.venue!=='espejos')return [];const m=metrics(s),v=[{x1:0,z1:m.D-4,x2:m.split,z2:m.D,label:'escenario'},{x1:0,z1:0,x2:m.split,z2:3.6,label:'zona lounge'},{x1:m.W-2.3,z1:0,x2:m.W,z2:3.8,label:'escalera'},{x1:m.split+.4,z1:m.D-1.6,x2:m.W-.4,z2:m.D,label:'barra de servicio'}];for(let z=4.5;z<m.D-3;z+=(m.D-7)/5)v.push({x1:m.split-.22,z1:z-.22,x2:m.split+.22,z2:z+.22,label:'columna'});return v}
function defaults(venue='encanto'){if(!names[venue])throw Error('Salón no válido');return venue==='espejos'?{version:1,venue,extent:'inside',hallW:16,hallD:28,stageH:.65,rampL:4.5,floorW:5.8,floorD:12,floorX:3.2,floorZ:14,floorAngle:0,tables:[]}:{version:1,venue,extent:'inside',stageH:.65,rampL:4.5,floorX:11.5,floorZ:10,floorAngle:0,tables:[]}}
const photos={};let pending;
function ready(venue){if(venue!=='espejos')return Promise.resolve();if(!pending)pending=Promise.all(['cascada','madera','piedra','logo'].map(k=>new Promise((resolve,reject)=>{const map=new T.Texture();map.colorSpace=T.SRGBColorSpace;photos[k]=map;const img=new Image();img.onload=()=>{map.image=img;map.needsUpdate=true;resolve()};img.onerror=()=>reject(Error('No se pudo cargar la textura de Espejos'));img.src=k==='logo'?'/assets/textures/jch-logo.png':'/assets/textures/espejos-'+k+'.jpg'}))).then(()=>undefined);return pending}
function buildEspejos(c){
 const {s,model,roofGroup,dimGroup,tableGroup,mat,box,beam,label,dim,makeTable}=c,m=metrics(s),{W,D,split}=m;
 const wood=mat(0xffffff,{map:photos.madera,roughness:.3}),stone=mat(0xffffff,{map:photos.piedra}),cream=mat(0xf3f1e9),dark=mat(0x262726),carpet=mat(0x54504f),mirror=mat(0xe4e9e7,{metalness:.85,roughness:.09}),glass=mat(0xb7d7d4,{transparent:true,opacity:.22,roughness:.2,metalness:.12}),white=mat(0xfffdf5),gold=mat(0xa87f42,{metalness:.45,roughness:.35});mirror.name='Espejo · Espejos';
 function canvas(kind){const cv=document.createElement('canvas');cv.width=cv.height=512;const g=cv.getContext('2d');if(kind==='tile'){g.fillStyle='#e8e7df';g.fillRect(0,0,512,512);g.strokeStyle='#756b5c';g.lineWidth=3;g.strokeRect(0,0,512,512);for(let i=0;i<1000;i++){const v=(i*179%511),u=(i*241%511);g.fillStyle='rgba(123,119,101,.035)';g.fillRect(v,u,2,2)}}else if(kind==='parquet'){for(let y=0;y<512;y+=64)for(let x=-128;x<512;x+=256){g.fillStyle=['#ac7849','#b98350','#c3925f','#a97043'][((x+128)/256+y/64)%4];g.fillRect(x+(y/64%2)*128,y,254,62);g.strokeStyle='rgba(68,35,12,.16)';for(let k=0;k<6;k++){g.beginPath();g.moveTo(x,y+k*9+3);g.lineTo(x+254,y+k*9+4);g.stroke()}}}else if(kind==='branches'){g.fillStyle='#d2eee9';g.fillRect(0,0,512,512);g.strokeStyle='#304c40';g.lineWidth=16;for(let i=0;i<8;i++){let x=i*70;g.beginPath();g.moveTo(x,512);g.bezierCurveTo(x+20,300,x-50,220,x+30,0);g.stroke();for(let j=0;j<4;j++){g.beginPath();g.moveTo(x+5,420-j*105);g.lineTo(x+(j%2?-60:65),350-j*105);g.stroke()}}}else if(kind==='logo'){g.fillStyle='#193e2b';g.fillRect(0,0,512,512);g.strokeStyle='#d9bc74';g.lineWidth=8;g.beginPath();g.arc(256,256,230,0,Math.PI*2);g.stroke();g.fillStyle='#eedcad';g.textAlign='center';g.font='34px Georgia';g.fillText('JARDINES',256,115);g.font='bold 160px Georgia';g.fillText('JCH',256,300);g.font='34px Georgia';g.fillText('CLUB HÍPICO',256,400)}const t=new T.CanvasTexture(cv);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;return t}
 const tile=mat(0xffffff,{map:canvas('tile'),roughness:.32}),parquet=mat(0xffffff,{map:canvas('parquet'),roughness:.36});tile.map.repeat.set((W-split)/.5,D/.5);parquet.map.repeat.set(split/2,Math.max(1,(D-8)/2));
 box(W,.25,D,W/2,-.18,D/2,mat(0xb9b9aa),model,'Base Espejos · dimensiones estimadas');
 // The main tiled area is raised; the wooden dance area and carpeted access
 // are lower. These levels are visible in the daylight conference photos.
 box(W-split,.4,D,(W+split)/2,.2,D/2,tile,model,'Loseta clara · área elevada');
 box(split,.045,D-8,split/2,.025,D/2,parquet,model,'Madera · área de baile en nivel bajo');
 box(split,.06,4,split/2,.015,2,carpet,model,'Alfombra lounge');box(split,s.stageH,4,split/2,s.stageH/2,D-2,carpet,model,'Escenario junto a ventanales');
 for(const z of [4.4,D-5.6]){box(.7,.2,1.5,split-.35,.1,z,white,model,'Peldaño de acceso');beam([split-.75,.85,z-.8],[split-.75,.85,z+.8],.045,wood);for(const zz of [z-.8,z+.8])beam([split-.75,0,zz],[split-.75,.85,zz],.04,wood)}
 // Mirror wall, varnished curved cornice and waterfall frieze.
 box(.25,3.7,D,W+.04,2.05,D/2,cream,model,'Muro lateral de espejos');
 for(let z=.25;z<D;z+=2.45){const d=Math.min(2.4,D-z);box(.035,1.9,d,W-.13,1.75,z+d/2,mirror,model,'Espejo lateral');box(.12,2.65,.075,W-.19,1.75,z,wood,model,'Marco de espejo')}
 function curvedCornice(x,z,length,rotation=0){const sh=new T.Shape();sh.moveTo(-.1,0);sh.quadraticCurveTo(-1,.18,-.8,.72);sh.lineTo(-.1,.72);sh.closePath();const mesh=new T.Mesh(new T.ExtrudeGeometry(sh,{depth:length,bevelEnabled:false,curveSegments:12}),wood);mesh.position.set(x,2.65,z);mesh.rotation.y=rotation;mesh.name='Cornisa curva de madera';mesh.castShadow=true;model.add(mesh)}
 curvedCornice(W-.05,0,D);box(.72,.58,D,W-.4,.7,D/2,wood,model,'Zócalo de madera');
 const frieze=mat(0xffffff,{map:photos.cascada});box(.04,.64,D-4,W-.16,3.73,(D+4)/2,frieze,model,'Friso de cascadas');
 for(let z=4;z<D-1;z+=2){const p=new T.Mesh(new T.ConeGeometry(.18,.5,7),mat(0x385a35));p.position.set(W-.55,3.5,z);p.name='Planta sobre cornisa';model.add(p)}
 // End wall uses dark irregular stone, interrupted by service doors and bar.
 box(W-split,3.1,.2,(W+split)/2,1.95,D+.08,stone,model,'Muro de fondo de piedra');
 for(const x of [split+.65,W-1.15])box(1.1,2.15,.12,x,1.48,D-.1,wood,model,'Puerta de servicio');
 curvedCornice(W-.05,D-.15,W-split,-Math.PI/2);
 // Daylight window wall and tied white curtains.
 box(.2,.62,D,.04,.3,D/2,cream,model,'Antepecho de ventanales');
 for(let z=.2;z<D;z+=2.6){const span=Math.min(2.55,D-z);box(.055,2.6,span,.05,1.95,z+span/2,glass,model,'Cristal de ventanal');box(.13,3.6,.13,.08,1.8,z,white,model,'Marco de ventanal');box(.13,.09,span,.08,1.45,z+span/2,white);for(const side of [-1,1]){const sh=new T.Shape();sh.moveTo(0,0);sh.lineTo(side*.65,2.45);sh.lineTo(side*.1,2.45);sh.lineTo(side*.04,0);const curtain=new T.Mesh(new T.ShapeGeometry(sh),new T.MeshStandardMaterial({color:0xfffdf4,side:T.DoubleSide,roughness:1}));curtain.rotation.y=Math.PI/2;curtain.position.set(.18,.7,z+span/2);curtain.name='Cortina blanca recogida';model.add(curtain)}}
 box(.12,.09,D,.08,3.45,D/2,white);box(.12,.08,D,.08,3.06,D/2,white);
 // Permanent structural columns remain visible even with the ceiling hidden.
 for(let z=4.5;z<D-3;z+=(D-7)/5){box(.34,3.7,.34,split,2.05,z,cream,model,'Columna estructural');box(.38,.75,.38,split,.775,z,wood);box(.38,.68,.38,split,3.45,z,wood);for(const x of [-1,1])box(.018,1.8,.345,split+x*.178,1.92,z,mirror,model,'Espejo de columna');const tv=box(.08,.7,1.15,split+.22,3.05,z,dark,model,'Pantalla sobre columna');tv.rotation.z=-.12;box(.2,.23,.25,split,3.65,z+.35,dark,model,'Luminaria de evento')}
 // Low white ceiling with faceted panels, downlights and linear event lighting.
 for(const [x,w,y] of [[split/2,split,3.65],[(W+split)/2,W-split,3.95]]){for(const side of [-1,1]){const geo=new T.BufferGeometry(),a=x+side*w/2;geo.setAttribute('position',new T.Float32BufferAttribute([a,y-.2,0,x,y+.08,0,a,y-.2,D,x,y+.08,D],3));geo.setIndex([0,1,2,1,3,2]);geo.computeVertexNormals();const panel=new T.Mesh(geo,mat(0xf3f1e9,{side:T.DoubleSide}));panel.name='Techo blanco facetado';roofGroup.add(panel)}for(let z=2;z<D;z+=3.8){box(w,.08,.08,x,y-.12,z,white,roofGroup,'Techo · viga');for(const xx of [x-w*.25,x+w*.25]){const light=new T.Mesh(new T.CylinderGeometry(.09,.09,.025,12),mat(0xfff7db,{emissive:0xffebbb,emissiveIntensity:.35}));light.position.set(xx,y-.1,z);light.name='Techo · luminaria empotrada';roofGroup.add(light)}}}
 for(const x of [split+.12,W-.7])box(.035,.025,D,x,3.7,D/2,mat(0xade9d4,{emissive:0x82bfa8,emissiveIntensity:.2}),roofGroup,'Techo · tira de iluminación');
 for(const z of [7,D-7]){beam([split,3.7,z],[split,3.05,z],.01,dark,roofGroup);const disco=new T.Mesh(new T.SphereGeometry(.18,12,8),mirror);disco.position.set(split,3.05,z);disco.name='Techo · esfera de espejo';roofGroup.add(disco)}
 // White arch at the internal access and the stairs immediately to its right.
 const archX=m.entryX,R=2.6,r=2.13,sh=new T.Shape();sh.absarc(0,0,R,0,Math.PI,false);sh.lineTo(-R,-.35);sh.lineTo(-r,-.35);sh.lineTo(-r,0);sh.absarc(0,0,r,Math.PI,0,true);sh.lineTo(R,-.35);const arch=new T.Mesh(new T.ExtrudeGeometry(sh,{depth:.3,bevelEnabled:false,curveSegments:36}),white);arch.position.set(archX,.75,.1);arch.name='Arco blanco interior';model.add(arch);for(const x of [archX-R+.2,archX+R-.2])box(.4,.8,.3,x,.75,.25,white);
 const logo=new T.Mesh(new T.CircleGeometry(.36,32),mat(0xffffff,{map:photos.logo,transparent:true}));logo.position.set(archX,3.02,.075);logo.rotation.y=Math.PI;logo.name='Emblema Jardines Club Hípico';model.add(logo);
 for(let i=0;i<12;i++)box(1.55,(i+1)*.18,.32,W-1.1,(i+1)*.09,3.8-i*.32,carpet,model,'Escalera lateral · peldaño '+(i+1));
 // Lounge sofas and white relief feature wall at the lower end.
 function sofa(x,z,angle=0,w=2.4){const g=new T.Group();g.position.set(x,0,z);g.rotation.y=angle;model.add(g);box(w,.35,.85,0,.27,0,white,g,'Sofá lounge');box(w,.8,.17,0,.58,.34,white,g);for(const xx of [-w/2+.1,w/2-.1])box(.18,.56,.85,xx,.47,0,white,g);for(const xx of [-w/2+.4,w/2-.4])box(.65,.4,.18,xx,.64,.2,cream,g,'Cojín lounge')}
 sofa(1.65,1.4);sofa(4.6,1.4,0,1.1);box(1.15,.35,.6,3,.2,2.5,dark,model,'Mesa de centro lounge');box(split,2.5,.13,split/2,1.3,-.12,cream,model,'Muro lounge en relieve');for(let x=.3;x<split;x+=.45)for(let y=.6;y<2.5;y+=.42){const tile=box(.28,.28,.1,x,y,-.025,white,model,'Relieve geométrico');tile.rotation.z=Math.PI/4}
 // Back bar: illuminated branch lattice, bottles and varnished counter.
 const barX=(split+W)/2,barW=W-split-1.3;box(barW,1.05,.65,barX,.925,D-.65,mat(0xffffff,{map:canvas('branches'),emissive:0x18382d,emissiveIntensity:.25}),model,'Barra de bebidas');box(barW+.2,.08,.82,barX,1.49,D-.65,wood,model,'Cubierta de barra');for(let row=0;row<3;row++){box(barW,.08,.32,barX,1.8+row*.35,D-.15,wood);for(let i=0;i<20;i++){const bottle=new T.Mesh(new T.CylinderGeometry(.04,.05,.2,6),mat(i%3?0x6d864a:0xb99c4f,{roughness:.3}));bottle.position.set(barX-barW/2+.2+i*(barW-.4)/20,1.94+row*.35,D-.16);bottle.name='Botella de barra';model.add(bottle)}}
 const branches=mat(0xffffff,{map:canvas('branches')});for(const z of [D-3.8,3.5])box(.08,1.1,2.8,.2,1.15,z,branches,model,'Panel decorativo de ramas');
 for(const x of [1.2,split-1.2]){box(.48,1,.48,x,s.stageH+.5,D-1.3,dark,model,'Bocina del escenario');beam([x,s.stageH,D-1.3],[x,s.stageH+1.2,D-1.3],.025,dark)}
 // Movable wooden dance floor; dimensions can be calibrated separately.
 const floorGroup=new T.Group(),floorDims=new T.Group();floorGroup.name='Pista móvil de madera';floorGroup.userData.isFloor=true;model.add(floorGroup);dimGroup.add(floorDims);
 const floorMat=mat(0xffffff,{map:canvas('parquet'),roughness:.35});floorMat.map.repeat.set(m.floorW/2,m.floorD/2);box(m.floorW,.055,m.floorD,0,.06,0,floorMat,floorGroup,'Pista de madera · medidas estimadas');
 const floorSelection=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(m.floorW+.06,.12,m.floorD+.06)),new T.LineBasicMaterial({color:0xb89737,depthTest:false}));floorSelection.position.y=.06;floorSelection.visible=false;floorSelection.renderOrder=90;floorGroup.add(floorSelection);
 for(const g of [floorGroup,floorDims]){g.position.set(s.floorX,surface(s,s.floorX,s.floorZ),s.floorZ);g.rotation.y=T.MathUtils.degToRad(s.floorAngle)}
 dim([-m.floorW/2,.13,-m.floorD/2-.35],[m.floorW/2,.13,-m.floorD/2-.35],m.floorW.toFixed(2)+' m*',[0,.7,-m.floorD/2-.6],floorDims);dim([m.floorW/2+.35,.13,-m.floorD/2],[m.floorW/2+.35,.13,m.floorD/2],m.floorD.toFixed(2)+' m*',[m.floorW/2+.6,.7,0],floorDims);label('PISTA DE MADERA',0,.5,0,.8,'#3b5041',floorDims);
 dim([0,.05,-.8],[W,.05,-.8],W.toFixed(1)+' m · estimado',[W/2,.7,-1.1]);dim([W+.9,.05,0],[W+.9,.05,D],D.toFixed(1)+' m · estimado',[W+1.2,.7,D/2]);label('ESCENARIO',split/2,s.stageH+.9,D-2,.8);label('BARRA',barX,2.1,D-.65,.65);label('ACCESO INTERIOR',archX,.6,-1.8,.9);label('ESPEJOS',W-.55,3.9,D/2,.9);
 s.tables.forEach(makeTable);return {floorGroup,floorDims,floorSelection};
}
window.JCHVenues={names,metrics,surface,obstacles,defaults,ready,photos,buildEspejos};
})();
