window.__viewerReady=false;window.__viewerError=null;
window.__showViewerError=function(message){window.__viewerError=String(message);document.getElementById('loading').hidden=false;document.getElementById('loadLabel').textContent=message;document.getElementById('retry').hidden=false;document.getElementById('retry').onclick=()=>location.reload()};
(function(){
'use strict';
const $=id=>document.getElementById(id), T=window.THREE;
const stage=$('stage'), loading=$('loading');
const coarse=matchMedia('(pointer:coarse)').matches;
const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
let renderer,scene,camera,root,ground,grid,key,fillLight,rim,hemi,ambient;
let glbBytes,modelBox,modelSize,meshes=[],stats={},textures=[],materials=[],clipPlane;
let ready=false,framePending=false,lastFrame=0,animation=null,toastTimer=0,currentView='general';
let activeLight='studio',walk=false,yaw=0,pitch=0,walkEye=new T.Vector3(),held=new Set(),pointers=new Map(),gesture=null,lastTap=null;
const orbit={target:new T.Vector3(),theta:.65,phi:.98,radius:45};
let tourTimer=0,touring=false,tourStep=0;
let defaultRadius=45,dragged=false,contextLost=false,shadowReady=false;
const raycaster=new T.Raycaster(),pointer=new T.Vector2();
const yieldFrame=()=>new Promise(resolve=>{const timer=setTimeout(resolve,40);requestAnimationFrame(()=>{clearTimeout(timer);resolve()})});
function progress(n,message){$('progress').style.width=n+'%';$('loadLabel').textContent=message;}
function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function requestRender(){if(!framePending&&!contextLost){framePending=true;requestAnimationFrame(render);}}
function updateCamera(){
 if(walk){camera.position.copy(walkEye);const dir=new T.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch));camera.lookAt(walkEye.clone().add(dir));}
 else{const s=Math.sin(orbit.phi);camera.position.set(orbit.target.x+orbit.radius*s*Math.sin(orbit.theta),orbit.target.y+orbit.radius*Math.cos(orbit.phi),orbit.target.z+orbit.radius*s*Math.cos(orbit.theta));camera.lookAt(orbit.target);}
 $('bearing').style.transform='rotate('+((walk?yaw:orbit.theta)*180/Math.PI)+'deg)';
 camera.updateMatrixWorld();
}
function render(now){
 framePending=false;if(!ready||contextLost)return;
 const dt=Math.min((now-lastFrame)/1000||.016,.05);lastFrame=now;
 if(animation){const t=Math.min(1,(now-animation.start)/animation.duration),e=1-Math.pow(1-t,3);orbit.target.lerpVectors(animation.from.target,animation.to.target,e);orbit.theta=animation.from.theta+(animation.to.theta-animation.from.theta)*e;orbit.phi=animation.from.phi+(animation.to.phi-animation.from.phi)*e;orbit.radius=animation.from.radius+(animation.to.radius-animation.from.radius)*e;if(t===1)animation=null;}
 if($('auto').checked&&!walk&&pointers.size===0&&!animation)orbit.theta+=dt*.16;
 if(walk&&held.size)moveWalk(dt);
 updateCamera();renderer.render(scene,camera);
 window.__viewerStats={...stats,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,view:currentView,walk,roof:$('roof').checked,wall:$('wall').checked,clipped:$('cut').checked,cutHeight:clipPlane.constant,camera:camera.position.toArray(),target:orbit.target.toArray(),radius:orbit.radius,light:activeLight,exposure:renderer.toneMappingExposure,tour:touring,tourStep,animating:!!animation,rendered:true};
 if(animation||($('auto').checked&&!walk)||(walk&&held.size))requestRender();
}
function setQuality(){const mode=$('quality').value;const ratio=mode==='low'?1:mode==='high'?Math.min(2.25,Math.max(1.5,devicePixelRatio||1)):Math.min(devicePixelRatio||1,coarse?1.5:2);renderer.setPixelRatio(ratio);renderer.setSize(stage.clientWidth,stage.clientHeight,false);requestRender();}
function resize(){if(!renderer)return;camera.aspect=stage.clientWidth/Math.max(1,stage.clientHeight);camera.updateProjectionMatrix();setQuality();if(ready&&['general','top','front','side'].includes(currentView)&&!walk&&pointers.size===0){defaultRadius=fitDistance(orbit.theta,orbit.phi,orbit.target);orbit.radius=defaultRadius;animation=null;}requestRender();}
function fitDistance(theta,phi,target){
 const dir=new T.Vector3(Math.sin(phi)*Math.sin(theta),Math.cos(phi),Math.sin(phi)*Math.cos(theta));
 const right=new T.Vector3().crossVectors(new T.Vector3(0,1,0),dir).normalize(),up=new T.Vector3().crossVectors(dir,right).normalize();
 const tanV=Math.tan(T.MathUtils.degToRad(camera.fov*.5)),tanH=tanV*camera.aspect;let d=0;
 const tx=root.position.x-target.x,ty=root.position.y-target.y,tz=root.position.z-target.z;
 for(const mesh of meshes){const a=mesh.geometry.attributes.position.array;for(let i=0;i<a.length;i+=3){const x=a[i]+tx,y=a[i+1]+ty,z=a[i+2]+tz;const depth=x*dir.x+y*dir.y+z*dir.z,h=Math.abs(x*right.x+y*right.y+z*right.z)/tanH,v=Math.abs(x*up.x+y*up.y+z*up.z)/tanV;d=Math.max(d,depth+Math.max(h,v));}}
 return d*(coarse?1.1:1.16)+.8;
}
function stopTour(){clearTimeout(tourTimer);tourTimer=0;touring=false;$('tour').setAttribute('aria-pressed','false');$('tour').querySelector('span').textContent='Recorrido';requestRender()}
function cancelMotion(){stopTour();animation=null;$('auto').checked=false;}
function tween(to){const from={target:orbit.target.clone(),theta:orbit.theta,phi:orbit.phi,radius:orbit.radius};while(to.theta-from.theta>Math.PI)to.theta-=Math.PI*2;while(to.theta-from.theta<-Math.PI)to.theta+=Math.PI*2;if(reduced){orbit.target.copy(to.target);Object.assign(orbit,{theta:to.theta,phi:to.phi,radius:to.radius});}else animation={from,to,start:performance.now(),duration:touring?1800:480};requestRender();}
function selectView(name,fromTour=false){
 if(!ready)return;if(!fromTour)cancelMotion();else{animation=null;$('auto').checked=false;}currentView=name;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));
 walk=name==='interior';held.clear();document.body.classList.toggle('walk-mode',walk);$('walkControls').hidden=!walk;camera.fov=walk?65:45;camera.near=walk?.025:.08;camera.updateProjectionMatrix();
 if(walk){setRoof(false);walkEye.set(1.5,1.98,10);yaw=-.035;pitch=-.025;requestRender();toast('Arrastra para mirar. Usa las flechas para recorrer el salón.');}
 else{const target=new T.Vector3(0,modelSize.y*.34,0),angles={general:[.65,.98],top:[0,.01],front:[0,1.42],side:[Math.PI/2,1.4]};const [theta,phi]=angles[name]||angles.general;if(name==='top')setRoof(false);const radius=fitDistance(theta,phi,target);defaultRadius=radius;tween({target,theta,phi,radius});}
}
function startTour(){if(!ready)return;if(reduced){toast('Activa las animaciones en tu dispositivo para reproducir el recorrido. Puedes explorar con los botones de vista.');return}stopTour();touring=true;tourStep=0;$('tour').setAttribute('aria-pressed','true');$('tour').querySelector('span').textContent='Pausar';const views=['general','front','side','top'];function next(){if(!touring)return;selectView(views[tourStep%views.length],true);if(tourStep%views.length===0)$('auto').checked=true;tourStep++;tourTimer=setTimeout(next,6000);requestRender()}next();toast('Recorrido automático · Toca Pausar o mueve la vista para detenerlo')}
function zoom(mult){if(!ready)return;if(walk){walkEye.add(new T.Vector3(Math.sin(yaw),0,-Math.cos(yaw)).multiplyScalar(mult<1?.7:-.7));}else{cancelMotion();orbit.radius=T.MathUtils.clamp(orbit.radius*mult,.35,400);}requestRender();}
function pan(dx,dy){const worldPerPixel=2*orbit.radius*Math.tan(T.MathUtils.degToRad(camera.fov/2))/Math.max(1,stage.clientHeight);const right=new T.Vector3().setFromMatrixColumn(camera.matrixWorld,0),up=new T.Vector3().setFromMatrixColumn(camera.matrixWorld,1);orbit.target.addScaledVector(right,-dx*worldPerPixel).addScaledVector(up,dy*worldPerPixel);}
function setRoof(show){$('roof').checked=show;$('roofQuick').setAttribute('aria-pressed',String(show));$('roofQuick').querySelector('span').textContent=show?'Ocultar cubierta':'Mostrar cubierta';meshes.filter(m=>m.userData.category==='roof').forEach(m=>m.visible=show);if(renderer)renderer.shadowMap.needsUpdate=true;requestRender();}
function setWall(show){meshes.filter(m=>m.userData.category==='wall').forEach(m=>m.visible=show);renderer.shadowMap.needsUpdate=true;requestRender();}
function setLights(preset){
 activeLight=preset;document.querySelectorAll('[data-light]').forEach(b=>b.classList.toggle('active',b.dataset.light===preset));
 const colors=preset==='warm'?[0xffd49a,0xffead4,0xf5dfb8]:preset==='day'?[0xfff3dc,0xe2edff,0xffffff]:[0xfffbf1,0xe8efff,0xffffff];
 key.color.setHex(colors[0]);fillLight.color.setHex(colors[1]);rim.color.setHex(colors[2]);hemi.color.setHex(preset==='warm'?0xffecd3:0xf3f7ff);hemi.groundColor.setHex(preset==='warm'?0xbdaa8f:0xa9ada0);
 const amount=Number($('fill').value)/100;hemi.intensity=1.65*amount;ambient.intensity=.3*amount;key.intensity=preset==='day'?3.3:2.8;fillLight.intensity=1.55*amount;rim.intensity=1.35*amount;renderer.toneMappingExposure=Number($('exposure').value)/100;requestRender();
}
function setClipping(){const enabled=$('cut').checked;clipPlane.constant=Number($('cutHeight').value);renderer.clippingPlanes=enabled?[clipPlane]:[];$('cutControls').hidden=!enabled;$('cutValue').textContent=Number($('cutHeight').value).toFixed(1)+' m';renderer.shadowMap.needsUpdate=true;requestRender();}
function setShadows(){renderer.shadowMap.enabled=$('shadows').checked;key.castShadow=$('shadows').checked;meshes.forEach(m=>{m.castShadow=$('shadows').checked;m.receiveShadow=$('shadows').checked;});ground.visible=$('shadows').checked;renderer.shadowMap.needsUpdate=true;requestRender();}
function setBackground(){const v=$('background').value;scene.background=new T.Color(v==='dark'?0x1e2925:v==='white'?0xffffff:0xf4f2ed);document.body.style.background=v==='dark'?'#1e2925':v==='white'?'#fff':'#f4f2ed';$('hint').style.color=v==='dark'?'#d1d7cd':'';requestRender();}
function moveWalk(dt){let x=0,z=0,y=0;if(held.has('forward')||held.has('w')||held.has('arrowup'))z+=1;if(held.has('back')||held.has('s')||held.has('arrowdown'))z-=1;if(held.has('left')||held.has('a')||held.has('arrowleft'))x-=1;if(held.has('right')||held.has('d')||held.has('arrowright'))x+=1;if(held.has('q'))y-=1;if(held.has('e'))y+=1;const speed=(held.has('shift')?5:2.8)*dt,n=Math.hypot(x,z)||1;walkEye.x+=(Math.sin(yaw)*z+Math.cos(yaw)*x)/n*speed;walkEye.z+=(-Math.cos(yaw)*z+Math.sin(yaw)*x)/n*speed;walkEye.y=T.MathUtils.clamp(walkEye.y+y*speed,.55,9);}
function rebaseGesture(){const pts=[...pointers.values()];gesture=pts.length>=2?{cx:(pts[0].x+pts[1].x)/2,cy:(pts[0].y+pts[1].y)/2,distance:Math.hypot(pts[1].x-pts[0].x,pts[1].y-pts[0].y)}:pts.length?{x:pts[0].x,y:pts[0].y}:null;}
function focusAt(x,y){
 if(walk||!ready)return;pointer.set(x/stage.clientWidth*2-1,-y/stage.clientHeight*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(meshes.filter(m=>m.visible),false).find(h=>!$('cut').checked||h.point.y<=Number($('cutHeight').value)+.01);if(!hit)return;
 const item=hit.object.userData.ranges.find(r=>hit.faceIndex>=r.start&&hit.faceIndex<r.end),name=item?item.name:'Detalle del salón';cancelMotion();currentView='detail';document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'));tween({target:hit.point.clone(),theta:orbit.theta,phi:Math.min(orbit.phi,1.3),radius:T.MathUtils.clamp(orbit.radius*.4,2.5,10)});toast(name==='Material'?'Detalle enfocado · R para volver':name+' · R para volver');
}
function setupInteractions(){
 const canvas=renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label','Arrastra para girar el modelo 3D. Usa la rueda o dos dedos para acercarte.');
 // Some mobile browsers suppress the next compatibility click after a 3D drag.
 // Activate a stationary touch on release, and discard only its duplicate click.
 const controlTouches=new Map(),activatedControls=new WeakMap();
 function touchControl(target){const button=target.closest('button');if(button&&!button.dataset.move)return {element:button,area:button};const input=target.closest('input[type="checkbox"]');if(input)return {element:input,area:input.closest('label')||input};const label=target.closest('label'),check=label&&label.querySelector('input[type="checkbox"]');return check?{element:check,area:label}:null;}
 document.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'&&e.pointerType!=='pen')return;const control=touchControl(e.target);if(control&&!control.element.disabled)controlTouches.set(e.pointerId,{...control,x:e.clientX,y:e.clientY});},true);
 document.addEventListener('pointerup',e=>{const control=controlTouches.get(e.pointerId);controlTouches.delete(e.pointerId);if(!control||Math.hypot(e.clientX-control.x,e.clientY-control.y)>12)return;const r=control.area.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;activatedControls.set(control.element,performance.now());control.element.click();},true);
 document.addEventListener('pointercancel',e=>controlTouches.delete(e.pointerId),true);
 document.addEventListener('click',e=>{const control=touchControl(e.target);if(control&&e.isTrusted&&e.detail>0&&performance.now()-(activatedControls.get(control.element)||-10000)<700){e.preventDefault();e.stopImmediatePropagation();}},true);
 canvas.addEventListener('contextmenu',e=>e.preventDefault());
 canvas.addEventListener('pointerdown',e=>{if(!ready)return;if(e.pointerType==='mouse')e.preventDefault();cancelMotion();if(!pointers.size)dragged=false;else dragged=true;canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,button:e.button,pan:e.button===2||e.button===1||e.shiftKey});rebaseGesture();});
 canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;if(e.pointerType==='mouse')e.preventDefault();const old=pointers.get(e.pointerId);if(Math.hypot(e.clientX-old.x,e.clientY-old.y)>2)dragged=true;pointers.set(e.pointerId,{...old,x:e.clientX,y:e.clientY});const pts=[...pointers.values()];
  if(pts.length>=2){const cx=(pts[0].x+pts[1].x)/2,cy=(pts[0].y+pts[1].y)/2,d=Math.hypot(pts[1].x-pts[0].x,pts[1].y-pts[0].y);if(!walk){if(d>0&&gesture.distance>0)orbit.radius=T.MathUtils.clamp(orbit.radius*gesture.distance/d,.35,400);pan(cx-gesture.cx,cy-gesture.cy);}else{walkEye.add(new T.Vector3(Math.sin(yaw),0,-Math.cos(yaw)).multiplyScalar((d-gesture.distance)*.018));}gesture={cx,cy,distance:d};}
  else{const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(walk){yaw-=dx*.005;pitch=T.MathUtils.clamp(pitch-dy*.005,-1.4,1.4);}else if(old.pan||e.shiftKey)pan(dx,dy);else{orbit.theta-=dx*.006;orbit.phi=T.MathUtils.clamp(orbit.phi-dy*.006,.01,1.55);}gesture={x:e.clientX,y:e.clientY};}requestRender();
 });
 function release(e){if(!pointers.has(e.pointerId))return;const single=pointers.size===1;pointers.delete(e.pointerId);rebaseGesture();if(single&&!dragged&&e.type==='pointerup'){const now=performance.now();if(lastTap&&now-lastTap.time<330&&Math.hypot(e.clientX-lastTap.x,e.clientY-lastTap.y)<28){focusAt(e.clientX,e.clientY);lastTap=null;}else lastTap={time:now,x:e.clientX,y:e.clientY};}}
 canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',e=>{dragged=true;release(e);});canvas.addEventListener('lostpointercapture',release);
 canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(T.MathUtils.clamp(e.deltaY,-160,160)*.0018));},{passive:false});
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>selectView(b.dataset.view));
 $('tour').onclick=()=>touring?stopTour():startTour();
 $('zoomIn').onclick=()=>zoom(.82);$('zoomOut').onclick=()=>zoom(1.22);$('roofQuick').onclick=()=>setRoof(!$('roof').checked);$('roof').onchange=()=>setRoof($('roof').checked);$('wall').onchange=()=>setWall($('wall').checked);
 const panelOpen=show=>{$('panel').hidden=!show;$('settings').setAttribute('aria-expanded',String(show));};$('settings').onclick=()=>panelOpen($('panel').hidden);$('closePanel').onclick=()=>panelOpen(false);
 $('exposure').oninput=()=>{$('exposureValue').textContent=$('exposure').value+' %';setLights(activeLight);};$('fill').oninput=()=>{$('fillValue').textContent=$('fill').value+' %';setLights(activeLight);};document.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>setLights(b.dataset.light));
 $('shadows').onchange=setShadows;$('cut').onchange=setClipping;$('cutHeight').oninput=setClipping;$('auto').onchange=()=>{if(walk&&$('auto').checked){$('auto').checked=false;toast('El giro automático está disponible en las vistas exteriores.');}requestRender();};$('grid').onchange=()=>{grid.visible=$('grid').checked;requestRender();};$('quality').onchange=setQuality;$('background').onchange=setBackground;
 const clean=show=>{document.body.classList.toggle('clean',show);panelOpen(false);};$('clean').onclick=()=>clean(true);$('restoreUI').onclick=()=>clean(false);
 async function fullscreen(){try{if(document.fullscreenElement){await document.exitFullscreen();}else if(document.documentElement.requestFullscreen){await document.documentElement.requestFullscreen();}else{clean(true);toast('Vista a pantalla completa. Pulsa Mostrar controles para volver.');}}catch(e){clean(true);toast('Vista limpia activada. Puedes seguir explorando.');}}
 $('fullscreen').onclick=fullscreen;
 $('capture').onclick=()=>{panelOpen(false);updateCamera();renderer.render(scene,camera);try{renderer.domElement.toBlob(blob=>{if(blob){saveBlob(blob,'Salon_Encanto_Vista_3D.png');toast('Imagen lista para guardar.');}else toast('El navegador no pudo crear la imagen.');},'image/png');}catch(e){toast('No se pudo guardar la imagen: '+e.message);}};
 $('downloadHTML').onclick=async()=>{const button=$('downloadHTML');button.disabled=true;try{await JCHShare.downloadViewer(new Uint8Array(glbBytes),presentation);toast('Visor HTML listo para guardar')}catch(e){toast(e.message)}finally{button.disabled=false}};
 $('downloadGLB').onclick=()=>saveBlob(new Blob([glbBytes],{type:'model/gltf-binary'}),'Salon_Encanto_base.glb');
 $('reset').onclick=()=>{setRoof(false);$('wall').checked=true;setWall(true);$('cut').checked=false;setClipping();$('grid').checked=false;grid.visible=false;$('exposure').value=100;$('fill').value=100;$('exposureValue').textContent='100 %';$('fillValue').textContent='100 %';$('shadows').checked=!coarse;setShadows();$('background').value='ivory';setBackground();$('quality').value='auto';setQuality();setLights('studio');selectView('general');toast('Vista y ajustes restablecidos.');};
 document.querySelectorAll('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')e.preventDefault();b.setPointerCapture(e.pointerId);held.add(b.dataset.move);requestRender();});const stop=()=>held.delete(b.dataset.move);b.addEventListener('pointerup',stop);b.addEventListener('pointercancel',stop);b.addEventListener('lostpointercapture',stop);});
 window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;const k=e.key.toLowerCase();if(k==='escape'){clean(false);panelOpen(false);if(walk)selectView('general');}else if(k==='h')clean(!document.body.classList.contains('clean'));else if(k==='f')fullscreen();else if(k==='r')selectView('general');else if(k==='+'||k==='=')zoom(.82);else if(k==='-')zoom(1.22);else if(walk&&['w','a','s','d','q','e','shift','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();held.add(k);requestRender();}});
 window.addEventListener('keyup',e=>held.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{held.clear();pointers.clear();gesture=null;});document.addEventListener('visibilitychange',()=>{held.clear();if(document.hidden)stopTour();if(!document.hidden)requestRender();});window.addEventListener('resize',resize);if(window.visualViewport)visualViewport.addEventListener('resize',resize);
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;window.__showViewerError('La memoria gráfica del navegador se liberó. Pulsa Volver a intentar para recargar el modelo.');});
 canvas.addEventListener('webglcontextrestored',()=>location.reload());
}
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function buildScene(){
 renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance',preserveDrawingBuffer:false});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.localClippingEnabled=true;stage.appendChild(renderer.domElement);
 scene=new T.Scene();scene.background=new T.Color(0xf4f2ed);camera=new T.PerspectiveCamera(45,stage.clientWidth/stage.clientHeight,.08,900);root=new T.Group();root.name='Salón Encanto';scene.add(root);
 ambient=new T.AmbientLight(0xffffff,.3);hemi=new T.HemisphereLight(0xf3f7ff,0xa9ada0,1.65);key=new T.DirectionalLight(0xfffbf1,2.8);key.position.set(-15,30,18);key.target.position.set(0,0,0);fillLight=new T.DirectionalLight(0xe8efff,1.55);fillLight.position.set(18,13,-6);rim=new T.DirectionalLight(0xffffff,1.35);rim.position.set(-6,14,-22);scene.add(ambient,hemi,key,key.target,fillLight,rim);
 key.shadow.mapSize.set(coarse?1024:2048,coarse?1024:2048);Object.assign(key.shadow.camera,{left:-27,right:27,top:27,bottom:-27,near:1,far:80});key.shadow.bias=-.00015;key.shadow.normalBias=.03;key.shadow.radius=3;
 ground=new T.Mesh(new T.PlaneGeometry(160,160),new T.ShadowMaterial({opacity:.16}));ground.rotation.x=-Math.PI/2;ground.position.y=-.012;ground.receiveShadow=true;ground.visible=false;scene.add(ground);
 grid=new T.GridHelper(80,80,0x9c9e91,0xd1d2c8);grid.position.y=-.006;grid.material.transparent=true;grid.material.opacity=.38;grid.visible=false;scene.add(grid);clipPlane=new T.Plane(new T.Vector3(0,-1,0),2.5);
 setQuality();setupInteractions();
}

let presentation={title:'Salón Encanto',date:'',venue:'encanto',settings:{}};
async function loadModelSource(){
 const embedded=$('modelData');if(embedded){$('downloadHTML').hidden=true;const config=$('presentationData');if(config)presentation=JCHShare.validatePresentation(JSON.parse(config.textContent));applyPresentation();return embedded.textContent.trim()}
 const hash=location.hash;if(hash.startsWith('#jch=')){
  presentation=await JCHShare.decode(hash.slice(5));await JCHModel.assetsReady;
  const venue=JCHModel.createVenue(presentation.layout);glbBytes=new Uint8Array(venue.glb());venue.dispose();applyPresentation();return null;
 }
 const response=await fetch('/assets/models/encanto-propuesta.glb.gz');if(!response.ok)throw Error('No se pudo abrir la propuesta del salón');if(typeof DecompressionStream==='undefined')throw Error('Actualiza tu navegador para abrir el modelo');glbBytes=new Uint8Array(await new Response(response.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer());applyPresentation();return null;
}
function applyPresentation(){document.title=presentation.title+' · JCH 3D';document.querySelector('.brand strong').textContent=presentation.title;document.querySelector('.brand span').textContent=presentation.date?presentation.date+' · JARDINES CLUB HÍPICO':'JARDINES CLUB HÍPICO · PRESENTACIÓN 3D';document.querySelector('.loadbox h1').textContent=presentation.title;const s=presentation.settings||{};if(s.light)activeLight=s.light;for(const k of ['exposure','fill','background','quality'])if(s[k]!==undefined)$(k).value=s[k];}

async function decodeModel(){
 const data=await loadModelSource();if(data===null)return decodeGLB();const total=data.length;glbBytes=new Uint8Array(Math.floor(total*3/4));let dest=0;
 for(let p=0;p<total;p+=1048576){const decoded=atob(data.slice(p,p+1048576));for(let n=0;n<decoded.length;n++)glbBytes[dest++]=decoded.charCodeAt(n);progress(5+Math.round(p/total*20),'Abriendo el modelo incluido…');if(p%3145728===0)await yieldFrame();}
 glbBytes=glbBytes.subarray(0,dest);$('modelData')?.remove();return decodeGLB();}
async function decodeGLB(){const dest=glbBytes.length;const dv=new DataView(glbBytes.buffer,glbBytes.byteOffset,glbBytes.byteLength);
 if(dv.getUint32(0,true)!==0x46546c67||dv.getUint32(4,true)!==2||dv.getUint32(8,true)!==dest)throw new Error('El GLB incluido no es válido.');
 let json,bin;for(let offset=12;offset<dest;){const len=dv.getUint32(offset,true),type=dv.getUint32(offset+4,true);offset+=8;if(type===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(glbBytes.subarray(offset,offset+len)).trim());else if(type===0x004e4942)bin=glbBytes.subarray(offset,offset+len);offset+=len;}
 if(!json||!bin)throw new Error('Faltan datos en el modelo.');if((json.extensionsRequired||[]).length)throw new Error('Esta versión no admite extensiones adicionales del GLB.');
 progress(30,'Preparando las texturas originales…');await loadTextures(json,bin);progress(48,'Construyendo el espacio y sus detalles…');await yieldFrame();
 const componentTypes={5120:Int8Array,5121:Uint8Array,5122:Int16Array,5123:Uint16Array,5125:Uint32Array,5126:Float32Array},itemSizes={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16};
 const accessorCache=new Map();
 function attr(index){if(accessorCache.has(index))return accessorCache.get(index);const a=json.accessors[index],v=json.bufferViews[a.bufferView],Ctor=componentTypes[a.componentType],size=itemSizes[a.type];if(!Ctor||!size)throw new Error('Formato de geometría no compatible.');const offset=bin.byteOffset+(v.byteOffset||0)+(a.byteOffset||0),stride=v.byteStride||size*Ctor.BYTES_PER_ELEMENT;let array;if(stride===size*Ctor.BYTES_PER_ELEMENT&&offset%Ctor.BYTES_PER_ELEMENT===0)array=new Ctor(bin.buffer,offset,a.count*size);else{array=new Ctor(a.count*size);for(let i=0;i<a.count;i++)array.set(new Ctor(bin.buffer.slice(offset+i*stride,offset+i*stride+size*Ctor.BYTES_PER_ELEMENT)),i*size);}const result=new T.BufferAttribute(array,size,!!a.normalized);accessorCache.set(index,result);return result;}
 const materialKeys=new Map();materials=(json.materials||[]).map((m,index)=>{const keyString=JSON.stringify({...m,name:undefined});if(materialKeys.has(keyString))return materialKeys.get(keyString);const p=m.pbrMetallicRoughness||{},c=p.baseColorFactor||[1,1,1,1],mat=new T.MeshStandardMaterial({color:new T.Color().fromArray(c),opacity:c[3],metalness:p.metallicFactor===undefined?1:p.metallicFactor,roughness:p.roughnessFactor===undefined?1:p.roughnessFactor,side:m.doubleSided?T.DoubleSide:T.FrontSide,transparent:m.alphaMode==='BLEND',alphaTest:m.alphaMode==='MASK'?(m.alphaCutoff===undefined?.5:m.alphaCutoff):0,depthWrite:m.alphaMode!=='BLEND'});if(p.baseColorTexture)mat.map=textures[p.baseColorTexture.index];if(p.metallicRoughnessTexture){const tex=textures[p.metallicRoughnessTexture.index].clone();tex.colorSpace=T.NoColorSpace;mat.roughnessMap=tex;mat.metalnessMap=tex;}if(m.emissiveFactor)mat.emissive.fromArray(m.emissiveFactor);if(m.emissiveTexture)mat.emissiveMap=textures[m.emissiveTexture.index];if(m.normalTexture){mat.normalMap=textures[m.normalTexture.index];const scale=m.normalTexture.scale||1;mat.normalScale.set(scale,scale);}mat.name=m.name||'Material';materialKeys.set(keyString,mat);return mat;});
 const buckets=new Map();let verts=0,sourceMeshes=0;
 function category(matName){if(/cubierta|techo/i.test(matName))return 'roof';if(/muro de fondo/i.test(matName))return 'wall';return 'main';}
 function node(index,parentMatrix){const n=json.nodes[index],matrix=new T.Matrix4();if(n.matrix)matrix.fromArray(n.matrix);else matrix.compose(new T.Vector3().fromArray(n.translation||[0,0,0]),new T.Quaternion().fromArray(n.rotation||[0,0,0,1]),new T.Vector3().fromArray(n.scale||[1,1,1]));matrix.premultiply(parentMatrix);if(n.mesh!==undefined){for(let p of json.meshes[n.mesh].primitives){if(p.mode!==undefined&&p.mode!==4)throw new Error('La geometría debe estar formada por triángulos.');let g=new T.BufferGeometry();for(let [k,v] of Object.entries(p.attributes)){const name={POSITION:'position',NORMAL:'normal',TEXCOORD_0:'uv',COLOR_0:'color'}[k];if(name)g.setAttribute(name,attr(v));}if(p.indices!==undefined){g.setIndex(attr(p.indices));g=g.toNonIndexed();}if(!g.attributes.normal)g.computeVertexNormals();if(!matrix.equals(new T.Matrix4())){g=g.clone();g.applyMatrix4(matrix);}const mat=materials[p.material]||new T.MeshStandardMaterial({color:0xe8dfce,roughness:.85,side:T.DoubleSide}),matName=(json.materials[p.material]||{}).name||n.name||'Detalle',cat=n.extras?.category||category(matName),key=mat.uuid+'|'+cat+'|'+!!g.attributes.uv;let bucket=buckets.get(key);if(!bucket){bucket={material:mat,category:cat,parts:[],count:0,ranges:[]};buckets.set(key,bucket);}const count=g.attributes.position.count;bucket.parts.push(g);bucket.ranges.push({start:bucket.count/3,end:(bucket.count+count)/3,name:matName});bucket.count+=count;verts+=count;sourceMeshes++;}}for(let child of n.children||[])node(child,matrix);}
 const mainScene=json.scenes[json.scene||0];for(let ni of mainScene.nodes)node(ni,new T.Matrix4());
 let done=0;for(let bucket of buckets.values()){const g=new T.BufferGeometry(),pos=new Float32Array(bucket.count*3),norm=new Float32Array(bucket.count*3),hasUV=!!bucket.parts[0].attributes.uv,uv=hasUV?new Float32Array(bucket.count*2):null;let offset=0;for(let part of bucket.parts){pos.set(part.attributes.position.array,offset*3);norm.set(part.attributes.normal.array,offset*3);if(uv)uv.set(part.attributes.uv.array,offset*2);offset+=part.attributes.position.count;}g.setAttribute('position',new T.BufferAttribute(pos,3));g.setAttribute('normal',new T.BufferAttribute(norm,3));if(uv)g.setAttribute('uv',new T.BufferAttribute(uv,2));g.computeBoundingBox();g.computeBoundingSphere();const mesh=new T.Mesh(g,bucket.material);mesh.name=bucket.category;mesh.userData={category:bucket.category,ranges:bucket.ranges};root.add(mesh);meshes.push(mesh);if(++done%6===0){progress(55+Math.round(done/buckets.size*30),'Optimizando los detalles para tu dispositivo…');await yieldFrame();}}
 const originalBox=new T.Box3().setFromObject(root),center=originalBox.getCenter(new T.Vector3());root.position.set(-center.x,-originalBox.min.y,-center.z);root.updateMatrixWorld(true);modelBox=new T.Box3().setFromObject(root);modelSize=modelBox.getSize(new T.Vector3());stats={sourceMeshes,renderMeshes:meshes.length,vertices:verts,textureCount:textures.length,modelBytes:glbBytes.length};$('modelInfo').textContent=sourceMeshes+' elementos · '+Math.round(verts/3).toLocaleString('es-MX')+' triángulos · '+(glbBytes.length/1048576).toFixed(1)+' MB de modelo original.';
}
async function loadTextures(json,bin){
 const images=await Promise.all((json.images||[]).map((img,index)=>new Promise((resolve,reject)=>{if(img.bufferView===undefined){reject(new Error('Las texturas externas no están incluidas.'));return;}const view=json.bufferViews[img.bufferView],bytes=bin.subarray(view.byteOffset||0,(view.byteOffset||0)+view.byteLength),url=URL.createObjectURL(new Blob([bytes],{type:img.mimeType||'image/png'})),image=new Image();const timer=setTimeout(()=>{URL.revokeObjectURL(url);reject(new Error('Una textura no respondió. Vuelve a abrir el archivo en Chrome o Safari.'));},20000);image.onload=()=>{clearTimeout(timer);URL.revokeObjectURL(url);resolve(image);};image.onerror=()=>{clearTimeout(timer);URL.revokeObjectURL(url);reject(new Error('No se pudo abrir la textura '+(index+1)+'.'));};image.src=url;})));
 textures=(json.textures||[]).map(t=>{const tex=new T.Texture(images[t.source]),sam=(json.samplers||[])[t.sampler]||{};tex.flipY=false;tex.colorSpace=T.SRGBColorSpace;const wrap={33071:T.ClampToEdgeWrapping,33648:T.MirroredRepeatWrapping,10497:T.RepeatWrapping},filter={9728:T.NearestFilter,9729:T.LinearFilter,9984:T.NearestMipmapNearestFilter,9985:T.LinearMipmapNearestFilter,9986:T.NearestMipmapLinearFilter,9987:T.LinearMipmapLinearFilter};tex.wrapS=wrap[sam.wrapS||10497];tex.wrapT=wrap[sam.wrapT||10497];tex.magFilter=filter[sam.magFilter||9729];tex.minFilter=filter[sam.minFilter||9987];tex.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());tex.needsUpdate=true;return tex;});
}
async function init(){
 try{progress(3,'Iniciando la vista 3D…');await yieldFrame();if(!T)throw new Error('El motor 3D no pudo iniciarse.');buildScene();await decodeModel();progress(92,'Encendiendo las luces del salón…');setRoof(!!presentation.settings?.roof);$('shadows').checked=presentation.settings?.shadows??!coarse;setShadows();setBackground();setLights(activeLight);$('exposureValue').textContent=$('exposure').value+' %';$('fillValue').textContent=$('fill').value+' %';ready=true;currentView='general';orbit.target.set(0,modelSize.y*.34,0);defaultRadius=fitDistance(orbit.theta,orbit.phi,orbit.target);orbit.radius=defaultRadius;updateCamera();await yieldFrame();renderer.render(scene,camera);progress(100,'Listo para explorar');window.__viewerReady=true;$('status').textContent='Modelo listo';loading.hidden=true;document.body.classList.add('model-ready');requestRender();}
 catch(err){console.error(err);const webgl=/WebGL|context|Error creating/.test(String(err));window.__showViewerError(webgl?'Este navegador no pudo activar la vista 3D. Abre el archivo descargado con Chrome, Edge, Firefox o Safari y activa la aceleración gráfica.':('No se pudo abrir el salón. '+err.message));}
}
if(location.protocol.startsWith('http')&&'serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
init();
})();
